
import os
basepath = '/Library/Frameworks/Mono.framework/Versions/2.4.2.3'

files = {
    os.path.join(basepath, 'lib', 'mono', 'gac', 'webkit-sharp', '1.9.0.0__a2b5f5c17ce02f1d'):['webkit-sharp.dll',],
    os.path.join(basepath, 'share', 'locale', 'bs', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Commons.Xml.Relaxng', '1.0.5000.0__0738eb9f132ed756'):['Commons.Xml.Relaxng.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Data.SybaseClient', '2.0.0.0__0738eb9f132ed756'):['Mono.Data.SybaseClient.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.WebServer2', '0.2.0.0__0738eb9f132ed756'):['Mono.WebServer2.dll',],
    os.path.join(basepath, 'lib', 'xsp', 'test', '1.1', 'customcontrol'):['index.aspx','tabcontrol.aspx','tabcontrol2.aspx',],
    os.path.join(basepath, 'share', 'locale', 'en_CA', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Novell.Directory.Ldap', '2.0.0.0__0738eb9f132ed756'):['Novell.Directory.Ldap.dll',],
    os.path.join(basepath, 'lib', 'xsp', 'test', 'controls'):['BreadCrumbs_1.1.ascx','BreadCrumbs_2.0.ascx','FileList.ascx','MonoSamplesHeader.ascx',],
    os.path.join(basepath, 'include', 'mono-1.0', 'mono', 'io-layer'):['access.h','atomic.h','collection.h','context.h','critical-sections.h','error.h','events.h','handles.h','io-layer.h','io-portability.h','io.h','macros.h','messages.h','mono-mutex.h','mutexes.h','processes.h','security.h','semaphores.h','sockets.h','status.h','system.h','threads.h','timefuncs.h','types.h','uglify.h','versioninfo.h','wait.h','wapi.h',],
    os.path.join(basepath, 'share', 'locale', 'fi', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.2.6.gtk-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.6.config','policy.2.6.gtk-sharp.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Accessibility', '2.0.0.0__b03f5f7f11d50a3a'):['Accessibility.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Management', '2.0.0.0__0738eb9f132ed756'):['Mono.Management.dll',],
    os.path.join(basepath, 'share', 'locale', 'si', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.2.6.pango-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.6.config','policy.2.6.pango-sharp.dll',],
    os.path.join(basepath, 'share', 'locale', 'ca', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'be@latin', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'IPCE', 'Lib', 'xml', 'dom'):['__init__.py','domreg.py','expatbuilder.py','minicompat.py','minidom.py','NodeFilter.py','pulldom.py','xmlbuilder.py',],
    os.path.join(basepath, 'share', 'locale', 'ca@valencia', 'LC_MESSAGES'):['gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.2.8.glib-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.8.config','policy.2.8.glib-sharp.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'ByteFX.Data', '0.7.6.2__0738eb9f132ed756'):['ByteFX.Data.dll',],
    os.path.join(basepath, 'share', 'locale', 'tk', 'LC_MESSAGES'):['gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'mai', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.IdentityModel.Selectors', '3.0.0.0__b77a5c561934e089'):['System.IdentityModel.Selectors.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Drawing', '2.0.0.0__b03f5f7f11d50a3a'):['System.Drawing.dll','System.Drawing.dll.config','System.Drawing.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Drawing.Design', '2.0.0.0__b03f5f7f11d50a3a'):['System.Drawing.Design.dll',],
    os.path.join(basepath, 'share', 'locale', 'wa', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Novell.Directory.Ldap', '1.0.5000.0__0738eb9f132ed756'):['Novell.Directory.Ldap.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Data.OracleClient', '1.0.5000.0__b77a5c561934e089'):['System.Data.OracleClient.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Configuration.Install', '2.0.0.0__b03f5f7f11d50a3a'):['System.Configuration.Install.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Configuration.Install', '1.0.5000.0__b03f5f7f11d50a3a'):['System.Configuration.Install.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.CompilerServices.SymbolWriter', '2.0.5.0__0738eb9f132ed756'):['Mono.CompilerServices.SymbolWriter.dll','Mono.CompilerServices.SymbolWriter.dll.mdb',],
    os.path.join(basepath, 'share', 'doc', 'packages', 'IPCE'):['License.html',],
    os.path.join(basepath, 'etc', 'mono', '2.0'):['DefaultWsdlHelpGenerator.aspx','machine.config','settings.map','web.config',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Microsoft.VisualBasic', '8.0.0.0__b03f5f7f11d50a3a'):['Microsoft.VisualBasic.dll','Microsoft.VisualBasic.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.ServiceProcess', '2.0.0.0__b03f5f7f11d50a3a'):['System.ServiceProcess.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Data.SqliteClient', '1.0.5000.0__0738eb9f132ed756'):['Mono.Data.SqliteClient.dll','Mono.Data.SqliteClient.dll.mdb',],
    os.path.join(basepath, 'share', 'pkgconfig'):['boo.pc','mono-addins-gui.pc','mono-addins-setup.pc','mono-addins.pc','xsp-2.pc','xsp.pc',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Web', '2.0.0.0__b03f5f7f11d50a3a'):['System.Web.dll','System.Web.dll.mdb',],
    os.path.join(basepath, 'include', 'mono-1.0', 'mono', 'utils'):['mono-codeman.h','mono-counters.h','mono-digest.h','mono-hash.h','mono-logger.h','mono-math.h','mono-membar.h','mono-path.h','mono-poll.h','mono-stdlib.h','mono-uri.h','monobitset.h',],
    os.path.join(basepath, 'lib', 'IPCE', 'Lib', 'test'):['__init__.py','pystone.py','test_support.py',],
    os.path.join(basepath, 'share', 'locale', 'pt_BR', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'io', 'LC_MESSAGES'):['gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'tr', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'xsp', 'test', '2.0', 'treeview', 'TreeLineImages'):['dash.gif','dashminus.gif','dashplus.gif','i.gif','l.gif','lminus.gif','lplus.gif','minus.gif','noexpand.gif','plus.gif','r.gif','rminus.gif','rplus.gif','t.gif','tminus.gif','tplus.gif',],
    os.path.join(basepath, 'lib', 'IPCE', 'ipy'):['ipy.exe','ipyw.exe','IronMath.dll','IronPython.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.2.4.gdk-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.4.config','policy.2.4.gdk-sharp.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Runtime.Remoting', '2.0.0.0__b77a5c561934e089'):['System.Runtime.Remoting.dll','System.Runtime.Remoting.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Transactions', '2.0.0.0__b77a5c561934e089'):['System.Transactions.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Boo.Lang.Useful', '2.0.9.1__32c39770e9a21a67'):['Boo.Lang.Useful.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'I18N', '1.0.5000.0__0738eb9f132ed756'):['I18N.dll','I18N.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.DirectoryServices', '1.0.5000.0__b03f5f7f11d50a3a'):['System.DirectoryServices.dll','System.DirectoryServices.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Data', '2.0.0.0__b77a5c561934e089'):['System.Data.dll','System.Data.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'RabbitMQ.Client', '2.0.0.0__b03f5f7f11d50a3a'):['RabbitMQ.Client.dll',],
    os.path.join(basepath, 'lib', 'xsp', 'test', '1.1', 'html'):['button.aspx','htmlanchor.aspx','htmlbutton.aspx','htmlgeneric.aspx','htmlimage.aspx','htmlinputbutton.aspx','htmlinputcheckbox.aspx','htmlinputfile.aspx','htmlinputhidden.aspx','htmlinputimage.aspx','htmlinputradiobutton.aspx','htmlinputtext.aspx','htmlselect.aspx','htmltable.aspx','htmltextarea.aspx','index.aspx',],
    os.path.join(basepath, 'lib', 'IPCE', 'Lib', 'Crypto', 'PublicKey', 'test'):['rsa_speed.py',],
    os.path.join(basepath, 'lib', 'xsp', 'test', '1.1'):['index.aspx',],
    os.path.join(basepath, 'etc', 'mono', '2.0', 'Browsers'):['Compat.browser',],
    os.path.join(basepath, 'share', 'locale', 'tl', 'LC_MESSAGES'):['glib20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'I18N.Other', '1.0.5000.0__0738eb9f132ed756'):['I18N.Other.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.ComponentModel.DataAnnotations', '3.5.0.0__31bf3856ad364e35'):['System.ComponentModel.DataAnnotations.dll',],
    os.path.join(basepath, 'share', 'locale', 'bn_IN', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'or', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'lt', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Web.Mvc', '1.0.0.0__31bf3856ad364e35'):['System.Web.Mvc.dll','System.Web.Mvc.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'gdk-sharp', '2.12.0.0__35e10195dab3c99f'):['gdk-sharp.dll','gdk-sharp.dll.config',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'ICSharpCode.SharpZipLib', '0.6.0.0__1b03e6acf1164f73'):['ICSharpCode.SharpZipLib.dll',],
    os.path.join(basepath, 'share', 'locale', 'eu', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Microsoft.Build.Utilities', '2.0.0.0__b03f5f7f11d50a3a'):['Microsoft.Build.Utilities.dll',],
    os.path.join(basepath, 'lib', 'xsp', 'test', '1.1', 'databind'):['databind-arraylist.aspx','databind-attribute.aspx','databind-class.aspx','databind-template.aspx','index.aspx',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'nunit.core.interfaces', '2.4.8.0__96d09a1eb7f44a77'):['nunit.core.interfaces.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Commons.Xml.Relaxng', '2.0.0.0__0738eb9f132ed756'):['Commons.Xml.Relaxng.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.2.10.atk-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.10.atk-sharp.dll','policy.2.10.config',],
    os.path.join(basepath, 'lib', 'monodoc'):['monodoc.xml',],
    os.path.join(basepath, 'share', 'NAnt', 'bin', 'lib', 'net', '2.0'):['NDoc.Core.dll','NDoc.Documenter.Msdn.dll','NDoc.ExtendedUI.dll','nunit.core.dll','nunit.framework.dll','nunit.util.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Configuration', '2.0.0.0__b03f5f7f11d50a3a'):['System.Configuration.dll','System.Configuration.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Messaging.RabbitMQ', '2.0.0.0__b03f5f7f11d50a3a'):['Mono.Messaging.RabbitMQ.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'I18N.MidEast', '2.0.0.0__0738eb9f132ed756'):['I18N.MidEast.dll',],
    os.path.join(basepath, 'share', 'locale', 'az', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'IPCE', 'Lib', 'xml', 'parsers'):['__init__.py','expat.py',],
    os.path.join(basepath, 'share', 'locale', 'pa', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'xsp', 'test'):['extensions.dll','favicon.ico','global.asax','index.aspx','index2.aspx','missing_components.aspx','mod-mono-server.exe.config','mono-powered-big.png','mono-xsp.css','mono.png','monobutton.png','sample.webapp','ServiceClient.exe','small-icon.png','web.config','Web.sitemap','xsp.exe.config',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'nunit.core.extensions', '2.4.8.0__96d09a1eb7f44a77'):['nunit.core.extensions.dll',],
    os.path.join(basepath, 'share', 'locale'):['locale.alias',],
    os.path.join(basepath, 'lib', 'IPCE', 'Lib', 'Crypto'):['__init__.py',],
    os.path.join(basepath, 'lib', 'gtk-2.0', 'modules'):['libferret.la','libferret.so','libgail.la','libgail.so',],
    os.path.join(basepath, 'lib', 'IPCE', 'Lib', 'compiler'):['__init__.py','ast.py','consts.py','visitor.py',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Microsoft.Build.Engine', '2.0.0.0__b03f5f7f11d50a3a'):['Microsoft.Build.Engine.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Management', '2.0.0.0__b03f5f7f11d50a3a'):['System.Management.dll',],
    os.path.join(basepath, 'share', 'locale', 'nb', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'pango-sharp', '2.12.0.0__35e10195dab3c99f'):['pango-sharp.dll','pango-sharp.dll.config',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Boo.Lang.Compiler', '2.0.9.1__32c39770e9a21a67'):['Boo.Lang.Compiler.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.0.3.Mono.Addins.Setup', '0.0.0.0__0738eb9f132ed756'):['policy.0.3.config','policy.0.3.Mono.Addins.Setup.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Posix', '1.0.5000.0__0738eb9f132ed756'):['Mono.Posix.dll','Mono.Posix.dll.config','Mono.Posix.dll.mdb',],
    os.path.join(basepath, 'share', 'locale', 'hi', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'zh_HK', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'xsp', '1.0'):['asp-state.exe','asp-state.exe.config','dbsessmgr.exe','dbsessmgr.exe.config',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Microsoft.JScript', '7.0.5000.0__b03f5f7f11d50a3a'):['Microsoft.JScript.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'IBM.Data.DB2', '1.0.0.0__7c307b91aa13d208'):['IBM.Data.DB2.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Data.Sqlite', '2.0.0.0__0738eb9f132ed756'):['Mono.Data.Sqlite.dll','Mono.Data.Sqlite.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.ServiceModel.Web', '3.0.0.0__31bf3856ad364e35'):['System.ServiceModel.Web.dll','System.ServiceModel.Web.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'I18N.Rare', '1.0.5000.0__0738eb9f132ed756'):['I18N.Rare.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Data.Linq', '3.5.0.0__b77a5c561934e089'):['System.Data.Linq.dll','System.Data.Linq.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Microsoft.Vsa', '7.0.5000.0__b03f5f7f11d50a3a'):['Microsoft.Vsa.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Data', '1.0.5000.0__0738eb9f132ed756'):['Mono.Data.dll','Mono.Data.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Npgsql', '1.0.5000.0__5d8b90d52f46fda7'):['Npgsql.dll',],
    os.path.join(basepath, 'share', 'doc', 'packages', 'xsp'):['NEWS','README',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Cecil.Mdb', '0.2.0.0__0738eb9f132ed756'):['Mono.Cecil.Mdb.dll','Mono.Cecil.Mdb.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', '2.1'):['Mono.CompilerServices.SymbolWriter.dll','mscorlib.dll','smcs.exe','System.Core.dll','System.dll','System.Net.dll','System.Runtime.Serialization.dll','System.ServiceModel.dll','System.ServiceModel.Web.dll','System.Xml.dll','System.Xml.Linq.dll',],
    os.path.join(basepath, 'lib', 'mono', '2.0'):['Accessibility.dll','al.exe','ByteFX.Data.dll','Commons.Xml.Relaxng.dll','cscompmgd.dll','csharp.exe','csharp.exe.mdb','CustomMarshalers.dll','fastcgi-mono-server2.exe','gacutil.exe','gacutil.exe.mdb','gmcs.exe','gmcs.exe.config','gmcs.exe.mdb','httpcfg.exe','I18N.CJK.dll','I18N.dll','I18N.MidEast.dll','I18N.Other.dll','I18N.Rare.dll','I18N.West.dll','IBM.Data.DB2.dll','ICSharpCode.SharpZipLib.dll','ilasm.exe','installutil.exe','mconfig.exe','mdoc.exe','Microsoft.Build.Engine.dll','Microsoft.Build.Framework.dll','Microsoft.Build.Tasks.dll','Microsoft.Build.Utilities.dll','Microsoft.Build.xsd','Microsoft.Common.targets','Microsoft.Common.tasks','Microsoft.CSharp.targets','Microsoft.JScript.dll','Microsoft.VisualBasic.dll','Microsoft.VisualBasic.targets','Microsoft.VisualC.dll','Microsoft.Vsa.dll','mkbundle.exe','mod-mono-server2.exe','mono-api-info.exe','mono-service.exe','mono-shlib-cop.exe','mono-shlib-cop.exe.config','Mono.C5.dll','Mono.Cairo.dll','Mono.CompilerServices.SymbolWriter.dll','Mono.CSharp.dll','Mono.Data.dll','Mono.Data.Sqlite.dll','Mono.Data.SqliteClient.dll','Mono.Data.SybaseClient.dll','Mono.Data.Tds.dll','Mono.Data.TdsClient.dll','Mono.GetOptions.dll','Mono.Http.dll','Mono.Management.dll','Mono.Messaging.dll','Mono.Messaging.RabbitMQ.dll','Mono.Posix.dll','Mono.Security.dll','Mono.Security.Win32.dll','Mono.Simd.dll','Mono.Web.dll','Mono.WebBrowser.dll','Mono.WebServer2.dll','monop.exe','mscorlib.dll','Novell.Directory.Ldap.dll','Npgsql.dll','nunit-console-runner.dll','nunit-console.exe','nunit-console.exe.config','nunit.core.dll','nunit.core.extensions.dll','nunit.core.interfaces.dll','nunit.framework.dll','nunit.framework.extensions.dll','nunit.mocks.dll','nunit.util.dll','OpenSystem.C.dll','PEAPI.dll','RabbitMQ.Client.dll','resgen.exe','sgen.exe','sqlsharp.exe','System.ComponentModel.DataAnnotations.dll','System.Configuration.dll','System.Configuration.Install.dll','System.Core.dll','System.Data.DataSetExtensions.dll','System.Data.dll','System.Data.Linq.dll','System.Data.OracleClient.dll','System.Design.dll','System.DirectoryServices.dll','System.dll','System.Drawing.Design.dll','System.Drawing.dll','System.EnterpriseServices.dll','System.IdentityModel.dll','System.IdentityModel.Selectors.dll','System.Management.dll','System.Messaging.dll','System.Runtime.Remoting.dll','System.Runtime.Serialization.dll','System.Runtime.Serialization.Formatters.Soap.dll','System.Security.dll','System.ServiceModel.dll','System.ServiceModel.Web.dll','System.ServiceProcess.dll','System.Transactions.dll','System.Web.Abstractions.dll','System.Web.dll','System.Web.DynamicData.dll','System.Web.Extensions.Design.dll','System.Web.Extensions.dll','System.Web.Mvc.dll','System.Web.Routing.dll','System.Web.Services.dll','System.Windows.Forms.dll','System.Xml.dll','System.Xml.Linq.dll','vbnc.exe','vbnc.rsp','wsdl.exe','xbuild.exe','xbuild.rsp','xsd.exe','xsp2.exe',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Cairo', '1.0.5000.0__0738eb9f132ed756'):['Mono.Cairo.dll','Mono.Cairo.dll.mdb',],
    os.path.join(basepath, 'share', 'man', 'man5'):['mdoc.5','mono-config.5',],
    os.path.join(basepath, 'lib', 'xsp', 'test', '1.1', 'webcontrols'):['calendar.aspx','datalist.aspx','dbpage1.aspx','dbpage1.sqlite','dbpage2.aspx','dbpage2.sqlite','dbpage_test_setup.exe','index.aspx','listitem.aspx','people.xml','peopletable.xsl','temperature.aspx','validator1.aspx','web_adrotator.aspx','web_adrotator.xml','web_button.aspx','web_checkbox.aspx','web_checkboxlist.aspx','web_comparevalidator.aspx','web_datagrid.aspx','web_datagrid_command.aspx','web_dropdownlist.aspx','web_hyperlink.aspx','web_image.aspx','web_imagebutton.aspx','web_label.aspx','web_linkbutton.aspx','web_listbox.aspx','web_literal.aspx','web_panel.aspx','web_placeholder.aspx','web_radiobutton.aspx','web_radiobuttonlist.aspx','web_regularexpressionvalidator.aspx','web_repeater.aspx','web_table.aspx','web_table2.aspx','web_textbox.aspx','web_xml.aspx',],
    os.path.join(basepath, 'share', 'mime', 'packages'):['boo-mime-info.xml',],
    os.path.join(basepath, 'share', 'locale', 'mi', 'LC_MESSAGES'):['gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'I18N.MidEast', '1.0.5000.0__0738eb9f132ed756'):['I18N.MidEast.dll',],
    os.path.join(basepath, 'share', 'locale', 'ast', 'LC_MESSAGES'):['gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.0.2.Mono.Addins', '0.0.0.0__0738eb9f132ed756'):['policy.0.2.config','policy.0.2.Mono.Addins.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.DirectoryServices', '2.0.0.0__b03f5f7f11d50a3a'):['System.DirectoryServices.dll','System.DirectoryServices.dll.mdb',],
    os.path.join(basepath, 'share', 'locale', 'sr@ije', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Web.Extensions.Design', '1.0.61025.0__31bf3856ad364e35'):['System.Web.Extensions.Design.dll','System.Web.Extensions.Design.dll.mdb',],
    os.path.join(basepath, 'bin'):['al','al1','al2','asp-state','asp-state1','asp-state2','booc','booi','booish','caspol','cert2spc','certmgr','chktrust','csharp','dbsessmgr','dbsessmgr1','dbsessmgr2','disco','dtd2rng','dtd2xsd','fastcgi-mono-server','fastcgi-mono-server1','fastcgi-mono-server2','gacutil','gacutil1','gacutil2','gdk-pixbuf-query-loaders','genxs','genxs1','gmcs','gtk-update-icon-cache','httpcfg','ilasm','ilasm1','ilasm2','installvst','ipy','ipy2','ipyw','ipyw2','jay','macpack','makecert','mautil','mconfig','mcs','mcs1','mdassembler','mdoc','mdoc-assemble','mdoc-export-html','mdoc-export-msxdoc','mdoc-update','mdoc-validate','mdvalidater','mkbundle','mkbundle1','mkbundle2','mod','mod-mono-server','mod-mono-server1','mod-mono-server2','mono','mono-api-info','mono-asp-apps','mono-cil-strip','mono-find-provides','mono-find-requires','mono-service','mono-service2','mono-shlib-cop','mono-test-install','mono-xmltool','monodis','monodocer','monodocs2html','monodocs2slashdoc','monograph','monolinker','monop','monop1','monop2','mozroots','nant','nunit-console','nunit-console2','pango-querymodules','pedump','permview','pkg-config','pkg-config.bin','prj2make','resgen','resgen1','resgen2','secutil','setreg','sgen','signcode','smcs','sn','soapsuds','sqlsharp','vbnc','wsdl','wsdl1','wsdl2','xbuild','xsd','xsd2','xsp','xsp1','xsp2',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Data.DataSetExtensions', '3.5.0.0__b77a5c561934e089'):['System.Data.DataSetExtensions.dll','System.Data.DataSetExtensions.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'monodoc'):['monodoc.dll',],
    os.path.join(basepath, 'share', 'NAnt', 'bin', 'lib', 'mono', '1.0'):['NDoc.Core.dll','NDoc.Documenter.Msdn.dll','NDoc.ExtendedUI.dll','nunit.core.dll','nunit.framework.dll','nunit.util.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Addins.Gui', '0.4.0.0__0738eb9f132ed756'):['Mono.Addins.Gui.dll','Mono.Addins.Gui.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Runtime.Serialization.Formatters.Soap', '1.0.5000.0__b03f5f7f11d50a3a'):['System.Runtime.Serialization.Formatters.Soap.dll','System.Runtime.Serialization.Formatters.Soap.dll.mdb',],
    os.path.join(basepath, 'share', 'locale', 'af', 'LC_MESSAGES'):['gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'mod-mono-server2', '2.4.2.0__0738eb9f132ed756'):['mod-mono-server2.exe','mod-mono-server2.exe.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.0.3.Mono.Addins.CecilReflector', '0.0.0.0__0738eb9f132ed756'):['policy.0.3.config','policy.0.3.Mono.Addins.CecilReflector.dll',],
    os.path.join(basepath, 'share', 'locale', 'am', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'Resources'):['Description.plist','Info.plist','version.plist',],
    os.path.join(basepath, 'lib', 'IPCE', 'Lib', 'Crypto', 'Util'):['__init__.py','number.py','randpool.py','RFC1751.py','test.py',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Data.Tds', '2.0.0.0__0738eb9f132ed756'):['Mono.Data.Tds.dll','Mono.Data.Tds.dll.mdb',],
    os.path.join(basepath, 'share', 'locale', 'et', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'nunit.util', '2.4.8.0__96d09a1eb7f44a77'):['nunit.util.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'nunit.framework', '2.4.8.0__96d09a1eb7f44a77'):['nunit.framework.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.ServiceModel.Web', '2.0.5.0__7cec85d7bea7798e'):['System.ServiceModel.Web.dll','System.ServiceModel.Web.dll.mdb',],
    os.path.join(basepath, 'share', 'NAnt', 'bin', 'lib', 'common', 'neutral'):['ICSharpCode.SharpCvsLib.Console.dll','ICSharpCode.SharpCvsLib.dll','ICSharpCode.SharpZipLib.dll','NUnitCore.dll',],
    os.path.join(basepath, 'lib', 'xsp', 'test', '1.1', 'authtest'):['index.aspx','login.aspx','web.config',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'OpenSystem.C', '2.0.0.0__b77a5c561934e089'):['OpenSystem.C.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.WebBrowser', '0.5.0.0__0738eb9f132ed756'):['Mono.WebBrowser.dll',],
    os.path.join(basepath, 'share', 'locale', 'eo', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Microsoft.VisualBasic', '7.0.5000.0__b03f5f7f11d50a3a'):['Microsoft.VisualBasic.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.WebServer', '0.1.0.0__0738eb9f132ed756'):['Mono.WebServer.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Microsoft.Vsa', '8.0.0.0__b03f5f7f11d50a3a'):['Microsoft.Vsa.dll',],
    os.path.join(basepath, 'share', 'locale', 'da', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'hu', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Boo.Lang.Extensions', '2.0.9.1__32c39770e9a21a67'):['Boo.Lang.Extensions.dll',],
    os.path.join(basepath, 'share', 'locale', 'it', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'I18N.West', '2.0.0.0__0738eb9f132ed756'):['I18N.West.dll',],
    os.path.join(basepath, 'share', 'locale', 'is', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Xml', '2.0.5.0__7cec85d7bea7798e'):['System.Xml.dll','System.Xml.dll.mdb',],
    os.path.join(basepath, 'share', 'locale', 'sq', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'I18N.CJK', '2.0.0.0__0738eb9f132ed756'):['I18N.CJK.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'fastcgi-mono-server2', '2.4.2.0__0738eb9f132ed756'):['fastcgi-mono-server2.exe','fastcgi-mono-server2.exe.mdb',],
    os.path.join(basepath, 'share', 'locale', 'pt', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Addins', '0.4.0.0__0738eb9f132ed756'):['Mono.Addins.dll','Mono.Addins.dll.config','Mono.Addins.dll.mdb',],
    os.path.join(basepath, 'share', 'locale', 'az_IR', 'LC_MESSAGES'):['gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'ar', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'ko', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'uk', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Boo.Lang.Parser', '2.0.9.1__32c39770e9a21a67'):['Boo.Lang.Parser.dll',],
    os.path.join(basepath, 'lib', 'xsp', 'test', '2.0', 'masterpages'):['content1.aspx','content2.aspx','frame.master','index.aspx','simple.aspx','simple.master',],
    os.path.join(basepath, 'share', 'locale', 'dz', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Data.SybaseClient', '1.0.5000.0__0738eb9f132ed756'):['Mono.Data.SybaseClient.dll',],
    os.path.join(basepath, 'share', 'locale', 'ku', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Microsoft.VisualC', '8.0.0.0__b03f5f7f11d50a3a'):['Microsoft.VisualC.dll',],
    os.path.join(basepath, 'share', 'locale', 'be', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'xh', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'gtk-2.0', '2.10.0', 'printbackends'):['libprintbackend-cups.la','libprintbackend-cups.so','libprintbackend-file.la','libprintbackend-file.so','libprintbackend-lpr.la','libprintbackend-lpr.so',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.2.10.glade-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.10.config','policy.2.10.glade-sharp.dll',],
    os.path.join(basepath, 'lib', 'mono', 'mono-addins'):['mautil.exe','Mono.Addins.CecilReflector.dll','Mono.Addins.dll','Mono.Addins.Gui.dll','Mono.Addins.Setup.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.CompilerServices.SymbolWriter', '1.0.5000.0__0738eb9f132ed756'):['Mono.CompilerServices.SymbolWriter.dll','Mono.CompilerServices.SymbolWriter.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.2.10.pango-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.10.config','policy.2.10.pango-sharp.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Boo.Lang.PatternMatching', '2.0.9.1__32c39770e9a21a67'):['Boo.Lang.PatternMatching.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Security', '1.0.5000.0__0738eb9f132ed756'):['Mono.Security.dll','Mono.Security.dll.mdb',],
    os.path.join(basepath, 'etc', 'pango'):['pango.modules',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Data', '2.0.0.0__0738eb9f132ed756'):['Mono.Data.dll','Mono.Data.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.ServiceModel', '2.0.5.0__31bf3856ad364e35'):['System.ServiceModel.dll','System.ServiceModel.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.2.4.gtk-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.4.config','policy.2.4.gtk-sharp.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'I18N', '2.0.0.0__0738eb9f132ed756'):['I18N.dll','I18N.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Web.Routing', '3.5.0.0__31bf3856ad364e35'):['System.Web.Routing.dll','System.Web.Routing.dll.mdb',],
    os.path.join(basepath, 'share', 'NAnt', 'bin', 'extensions', 'common', '2.0'):['NAnt.MSBuild.dll','NAnt.MSBuild.dll.mdb','NAnt.MSBuild.xml',],
    os.path.join(basepath, 'lib', 'IPCE', 'Lib', 'Crypto', 'PublicKey'):['__init__.py','DSA.py','ElGamal.py','pubkey.py','qNEW.py','RSA.py',],
    os.path.join(basepath, 'lib', 'pango', '1.6.0', 'modules'):['pango-arabic-lang.so','pango-basic-atsui.so','pango-indic-lang.so',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Security', '1.0.5000.0__b03f5f7f11d50a3a'):['System.Security.dll','System.Security.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'fastcgi-mono-server', '2.4.2.0__0738eb9f132ed756'):['fastcgi-mono-server.exe','fastcgi-mono-server.exe.mdb',],
    os.path.join(basepath, 'share', 'locale', 'hy', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'as', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'atk-sharp', '2.12.0.0__35e10195dab3c99f'):['atk-sharp.dll','atk-sharp.dll.config',],
    os.path.join(basepath, 'share', 'locale', 'te', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'lv', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'nunit.core', '2.4.8.0__96d09a1eb7f44a77'):['nunit.core.dll',],
    os.path.join(basepath, 'lib', 'mono', 'compat-1.0'):['ICSharpCode.SharpZipLib.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.2.4.glib-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.4.config','policy.2.4.glib-sharp.dll',],
    os.path.join(basepath, 'share', 'locale', 'nn', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'xsp2', '2.4.2.0__0738eb9f132ed756'):['xsp2.exe','xsp2.exe.mdb',],
    os.path.join(basepath, 'share', 'locale', 'uz@cyrillic', 'LC_MESSAGES'):['gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Xml', '2.0.0.0__b77a5c561934e089'):['System.Xml.dll','System.Xml.dll.mdb',],
    os.path.join(basepath, 'share', 'locale', 'sr@latin', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'etc', 'mono', 'mconfig'):['config.xml',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.EnterpriseServices', '2.0.0.0__b03f5f7f11d50a3a'):['System.EnterpriseServices.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Cecil', '0.6.9.0__0738eb9f132ed756'):['Mono.Cecil.dll','Mono.Cecil.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.0.2.Mono.Addins.CecilReflector', '0.0.0.0__0738eb9f132ed756'):['policy.0.2.config','policy.0.2.Mono.Addins.CecilReflector.dll',],
    os.path.join(basepath, 'share', 'locale', 'sk', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Data.OracleClient', '2.0.0.0__b77a5c561934e089'):['System.Data.OracleClient.dll','System.Data.OracleClient.dll.mdb',],
    os.path.join(basepath, 'share', 'locale', 'tt', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gtk-sharp-2.0'):['atk-sharp.dll','gdk-sharp.dll','glade-sharp.dll','glib-sharp.dll','gtk-sharp.dll','pango-sharp.dll','policy.2.10.atk-sharp.dll','policy.2.10.gdk-sharp.dll','policy.2.10.glade-sharp.dll','policy.2.10.glib-sharp.dll','policy.2.10.gtk-sharp.dll','policy.2.10.pango-sharp.dll','policy.2.4.atk-sharp.dll','policy.2.4.gdk-sharp.dll','policy.2.4.glade-sharp.dll','policy.2.4.glib-sharp.dll','policy.2.4.gtk-sharp.dll','policy.2.4.pango-sharp.dll','policy.2.6.atk-sharp.dll','policy.2.6.gdk-sharp.dll','policy.2.6.glade-sharp.dll','policy.2.6.glib-sharp.dll','policy.2.6.gtk-sharp.dll','policy.2.6.pango-sharp.dll','policy.2.8.atk-sharp.dll','policy.2.8.gdk-sharp.dll','policy.2.8.glade-sharp.dll','policy.2.8.glib-sharp.dll','policy.2.8.gtk-sharp.dll','policy.2.8.pango-sharp.dll',],
    os.path.join(basepath, 'lib', 'mono-source-libs'):['getline.cs','Options.cs',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'mono-service', '1.0.5000.0__0738eb9f132ed756'):['mono-service.exe',],
    os.path.join(basepath, 'share', 'locale', 'id', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'ta', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Security', '2.0.0.0__0738eb9f132ed756'):['Mono.Security.dll','Mono.Security.dll.mdb',],
    os.path.join(basepath, 'share', 'locale', 'he', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.0.2.Mono.Addins.Setup', '0.0.0.0__0738eb9f132ed756'):['policy.0.2.config','policy.0.2.Mono.Addins.Setup.dll',],
    os.path.join(basepath, 'share', 'locale', 'hr', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Web.Extensions', '3.5.0.0__31bf3856ad364e35'):['System.Web.Extensions.dll','System.Web.Extensions.dll.mdb',],
    os.path.join(basepath, 'share', 'locale', 'ml', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'vi', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'NAnt', 'bin', 'lib', 'net', '1.0'):['NDoc.Core.dll','NDoc.Documenter.Msdn.dll','NDoc.ExtendedUI.dll','nunit.core.dll','nunit.framework.dll','nunit.util.dll',],
    os.path.join(basepath, 'share', 'NAnt', 'bin', 'lib', 'net', '1.1'):['NDoc.Core.dll','NDoc.Documenter.Msdn.dll','NDoc.ExtendedUI.dll','nunit.core.dll','nunit.framework.dll','nunit.util.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Data.TdsClient', '2.0.0.0__0738eb9f132ed756'):['Mono.Data.TdsClient.dll','Mono.Data.TdsClient.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'boo'):['Boo.Lang.CodeDom.dll','Boo.Lang.Compiler.dll','Boo.Lang.dll','Boo.Lang.Extensions.dll','Boo.Lang.Interpreter.dll','Boo.Lang.Parser.dll','Boo.Lang.PatternMatching.dll','Boo.Lang.Useful.dll',],
    os.path.join(basepath, 'lib', 'IPCE', 'Lib', 'xml', 'sax'):['__init__.py','_exceptions.py','expatreader.py','handler.py','saxutils.py','xmlreader.py',],
    os.path.join(basepath, 'lib', 'IPCE', 'ipy2', 'Lib'):['site.py',],
    os.path.join(basepath, 'lib', 'xsp', 'test', '2.0', 'gridview'):['BasicGrid.aspx','data.xml','index.aspx','ObjectBoundGrid.aspx',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'ICSharpCode.SharpZipLib', '0.84.0.0__1b03e6acf1164f73'):['ICSharpCode.SharpZipLib.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Web', '1.0.5000.0__b03f5f7f11d50a3a'):['System.Web.dll','System.Web.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Messaging', '2.0.0.0__b03f5f7f11d50a3a'):['System.Messaging.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Messaging', '1.0.5000.0__b03f5f7f11d50a3a'):['System.Messaging.dll',],
    os.path.join(basepath, 'lib', 'IPCE', 'Lib', 'elementtree'):['__init__.py','ElementInclude.py','ElementPath.py','ElementTree.py','HTMLTreeBuilder.py','SgmlopXMLTreeBuilder.py','SimpleXMLTreeBuilder.py','SimpleXMLWriter.py','TidyHTMLTreeBuilder.py','TidyTools.py','XMLTreeBuilder.py',],
    os.path.join(basepath, 'lib', 'xsp', 'test', '1.1', 'asp.net'):['body.inc','browsercaps.aspx','code-render.aspx','codebehind1.aspx','header.inc','includetest.aspx','index.aspx','registertest.aspx','registertest1.ascx','registertest2.ascx','serial.aspx','server-side-object.aspx','session1.aspx','transfer1.aspx','transfer2.aspx','typedesc.aspx',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Management', '1.0.5000.0__b03f5f7f11d50a3a'):['System.Management.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.IdentityModel', '3.0.0.0__b77a5c561934e089'):['System.IdentityModel.dll',],
    os.path.join(basepath, 'lib', 'IPCE', 'Lib', 'xml'):['__init__.py',],
    os.path.join(basepath, 'lib', 'gtk-2.0', '2.10.0', 'loaders'):['libpixbufloader-ani.la','libpixbufloader-ani.so','libpixbufloader-bmp.la','libpixbufloader-bmp.so','libpixbufloader-gif.la','libpixbufloader-gif.so','libpixbufloader-icns.la','libpixbufloader-icns.so','libpixbufloader-ico.la','libpixbufloader-ico.so','libpixbufloader-jpeg.la','libpixbufloader-jpeg.so','libpixbufloader-pcx.la','libpixbufloader-pcx.so','libpixbufloader-png.la','libpixbufloader-png.so','libpixbufloader-pnm.la','libpixbufloader-pnm.so','libpixbufloader-ras.la','libpixbufloader-ras.so','libpixbufloader-tga.la','libpixbufloader-tga.so','libpixbufloader-tiff.la','libpixbufloader-tiff.so','libpixbufloader-wbmp.la','libpixbufloader-wbmp.so','libpixbufloader-xbm.la','libpixbufloader-xbm.so','libpixbufloader-xpm.la','libpixbufloader-xpm.so',],
    os.path.join(basepath, 'share', 'locale', 'ne', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'IPCE', 'Lib', 'Crypto', 'Protocol'):['__init__.py','AllOrNothing.py','Chaffing.py',],
    os.path.join(basepath, 'lib', 'IPCE', 'Lib'):['__future__.py','_codecs_errors.py','_fileobject.py','_LWPCookieJar.py','_MozillaCookieJar.py','_pth_support.py','_sre.py','_threading_local.py','array.py','atexit.py','base64.py','BaseHTTPServer.py','bdb.py','BeautifulSoup.py','binhex.py','bisect.py','calendar.py','cgi.py','cmd.py','code.py','codecs.py','codeop.py','ConfigParser.py','Cookie.py','cookielib.py','copy.py','copy_reg.py','ctypes.py','dbapi.py','decimal.py','difflib.py','dis.py','fileinput.py','fnmatch.py','formatter.py','ftplib.py','getopt.py','getpass.py','gettext.py','glob.py','gopherlib.py','hashlib.py','heapq.py','hmac.py','htmlentitydefs.py','htmllib.py','httplib.py','ihooks.py','inspect.py','irclib.py','keyword.py','linecache.py','locale.py','macurl2path.py','mailbox.py','markupbase.py','md5.py','mimetools.py','mimetypes.py','modulefinder.py','MySQLdb.py','netrc.py','new.py','nntplib.py','ntpath.py','nturl2path.py','odbc.py','opcode.py','optparse.py','os.py','pdb.py','pickle.py','pkgutil.py','platform.py','poplib.py','posixpath.py','pprint.py','psycopg.py','pyexpat.py','Queue.py','quopri.py','random.py','repr.py','rfc822.py','select.py','sets.py','sgmllib.py','sha.py','shlex.py','shutil.py','signal.py','SimpleHTTPServer.py','smtplib.py','socket.py','SocketServer.py','sqlclient.py','sqlite.py','sqlite3.py','sre.py','sre_compile.py','sre_constants.py','sre_parse.py','ssl.py','stat.py','string.py','StringIO.py','tarfile.py','tempfile.py','textwrap.py','this.py','threading.py','token.py','tokenize.py','traceback.py','types.py','unittest.py','urllib.py','urllib2.py','urlparse.py','UserDict.py','UserList.py','UserString.py','warnings.py','weakref.py','wsgi.py','xmlrpclib.py','zlib.py',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'I18N.West', '1.0.5000.0__0738eb9f132ed756'):['I18N.West.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Runtime.Serialization', '2.0.5.0__7cec85d7bea7798e'):['System.Runtime.Serialization.dll','System.Runtime.Serialization.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.2.8.glade-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.8.config','policy.2.8.glade-sharp.dll',],
    os.path.join(basepath, 'share', 'locale', 'yi', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'xsp', 'test', 'App_Code'):['Application.cs',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'cscompmgd', '7.0.5000.0__b03f5f7f11d50a3a'):['cscompmgd.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Core', '3.5.0.0__b77a5c561934e089'):['System.Core.dll','System.Core.dll.mdb',],
    os.path.join(basepath, 'share', 'locale', 'de', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo','mcs.mo',],
    os.path.join(basepath, 'lib', 'IPCE', 'Lib', 'email', 'test', 'data'):['audiotest.au','msg_01.txt','msg_02.txt','msg_03.txt','msg_04.txt','msg_05.txt','msg_06.txt','msg_07.txt','msg_08.txt','msg_09.txt','msg_10.txt','msg_11.txt','msg_12.txt','msg_12a.txt','msg_13.txt','msg_14.txt','msg_15.txt','msg_16.txt','msg_17.txt','msg_18.txt','msg_19.txt','msg_20.txt','msg_21.txt','msg_22.txt','msg_23.txt','msg_24.txt','msg_25.txt','msg_26.txt','msg_27.txt','msg_28.txt','msg_29.txt','msg_30.txt','msg_31.txt','msg_32.txt','msg_33.txt','msg_34.txt','msg_35.txt','msg_36.txt','msg_37.txt','msg_38.txt','msg_39.txt','msg_40.txt','msg_41.txt','msg_42.txt','msg_43.txt','msg_44.txt','PyBanner048.gif',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System', '2.0.0.0__b77a5c561934e089'):['System.dll','System.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Boo.Lang', '2.0.9.1__32c39770e9a21a67'):['Boo.Lang.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Security.Win32', '2.0.0.0__0738eb9f132ed756'):['Mono.Security.Win32.dll',],
    os.path.join(basepath, 'include', 'mono-1.0', 'mono', 'interpreter'):['embed.h',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'I18N.Other', '2.0.0.0__0738eb9f132ed756'):['I18N.Other.dll',],
    os.path.join(basepath, 'lib', 'IPCE', 'Lib', 'paramiko'):['__init__.py','agent.py','auth_handler.py','ber.py','buffered_pipe.py','channel.py','client.py','common.py','compress.py','config.py','dsskey.py','file.py','hostkeys.py','kex_gex.py','kex_group1.py','logging22.py','message.py','packet.py','pipe.py','pkey.py','primes.py','resource.py','rsakey.py','server.py','sftp.py','sftp_attr.py','sftp_client.py','sftp_file.py','sftp_handle.py','sftp_server.py','sftp_si.py','ssh_exception.py','transport.py','util.py','win_pageant.py',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.2.8.pango-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.8.config','policy.2.8.pango-sharp.dll',],
    os.path.join(basepath, 'share', 'locale', 'zh_TW', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'mg', 'LC_MESSAGES'):['glib20.mo',],
    os.path.join(basepath, 'lib', 'glib-2.0', 'include'):['glibconfig.h','glibconfig.ppc.h','glibconfig.x86.h',],
    os.path.join(basepath, 'lib', 'IPCE', 'Lib', 'wsgiref'):['__init__.py','handlers.py','headers.py','simple_server.py','util.py','validate.py',],
    os.path.join(basepath, 'lib', 'xsp', 'test', 'bin'):['codebehind1.dll','extensions.dll','SiteMapReader_1.1.dll','tabcontrol.dll','tabcontrol2.dll','treeview.dll','typedesc.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'monodoc', '1.0.0.0__0738eb9f132ed756'):['monodoc.dll','monodoc.dll.config',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.2.6.glib-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.6.config','policy.2.6.glib-sharp.dll',],
    os.path.join(basepath, 'share', 'locale', 'fa', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'oc', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'CustomMarshalers', '2.0.0.0__b03f5f7f11d50a3a'):['CustomMarshalers.dll',],
    os.path.join(basepath, 'share', 'locale', 'ia', 'LC_MESSAGES'):['gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Microsoft.JScript', '8.0.0.0__b03f5f7f11d50a3a'):['Microsoft.JScript.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.0.3.Mono.Addins.Gui', '0.0.0.0__0738eb9f132ed756'):['policy.0.3.config','policy.0.3.Mono.Addins.Gui.dll',],
    os.path.join(basepath, 'lib', 'mono', '1.0'):['Accessibility.dll','al.exe','browsercaps-updater.exe','ByteFX.Data.dll','caspol.exe','cert2spc.exe','certmgr.exe','chktrust.exe','cilc.exe','Commons.Xml.Relaxng.dll','cscompmgd.dll','culevel.exe','CustomMarshalers.dll','disco.exe','dtd2rng.exe','dtd2xsd.exe','fastcgi-mono-server.exe','FirebirdSql.Data.Firebird.dll','gacutil.exe','genxs.exe','I18N.CJK.dll','I18N.dll','I18N.MidEast.dll','I18N.Other.dll','I18N.Rare.dll','I18N.West.dll','IBM.Data.DB2.dll','ICSharpCode.SharpZipLib.dll','ictool.exe','ilasm.exe','installutil.exe','installvst.exe','macpack.exe','makecert.exe','mcs.exe','mcs.exe.config','mcs.exe.mdb','Microsoft.JScript.dll','Microsoft.VisualBasic.dll','Microsoft.VisualC.dll','Microsoft.Vsa.dll','mjs.exe','mkbundle.exe','mod-mono-server.exe','mod.exe','mono-cil-strip.exe','mono-service.exe','mono-xmltool.exe','Mono.Cairo.dll','Mono.CompilerServices.SymbolWriter.dll','Mono.Data.dll','Mono.Data.Sqlite.dll','Mono.Data.SqliteClient.dll','Mono.Data.SybaseClient.dll','Mono.Data.Tds.dll','Mono.Data.TdsClient.dll','Mono.GetOptions.dll','Mono.Http.dll','Mono.Messaging.dll','Mono.Messaging.RabbitMQ.dll','Mono.Posix.dll','Mono.Security.dll','Mono.Security.Win32.dll','Mono.WebBrowser.dll','Mono.WebServer.dll','monolinker.exe','monop.exe','mozroots.exe','mscorlib.dll','Novell.Directory.Ldap.dll','Npgsql.dll','nunit-console-runner.dll','nunit-console.exe','nunit-console.exe.config','nunit.core.dll','nunit.core.extensions.dll','nunit.core.interfaces.dll','nunit.framework.dll','nunit.framework.extensions.dll','nunit.mocks.dll','nunit.util.dll','OpenSystem.C.dll','PEAPI.dll','permview.exe','prj2make.exe','RabbitMQ.Client.dll','resgen.exe','secutil.exe','setreg.exe','signcode.exe','sn.exe','soapsuds.exe','System.Configuration.Install.dll','System.Data.dll','System.Data.OracleClient.dll','System.Design.dll','System.DirectoryServices.dll','System.dll','System.Drawing.Design.dll','System.Drawing.dll','System.EnterpriseServices.dll','System.Management.dll','System.Messaging.dll','System.Runtime.Remoting.dll','System.Runtime.Serialization.Formatters.Soap.dll','System.Security.dll','System.ServiceProcess.dll','System.Web.dll','System.Web.Services.dll','System.Windows.Forms.dll','System.Xml.dll','wsdl.exe','xsd.exe','xsp.exe',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Boo.Lang.CodeDom', '2.0.9.1__32c39770e9a21a67'):['Boo.Lang.CodeDom.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Design', '1.0.5000.0__b03f5f7f11d50a3a'):['System.Design.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'PEAPI', '1.0.5000.0__0738eb9f132ed756'):['PEAPI.dll',],
    os.path.join(basepath, 'share', 'locale', 'sr', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'IPCE', 'ipy', 'Lib'):['site.py',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Drawing', '1.0.5000.0__b03f5f7f11d50a3a'):['System.Drawing.dll','System.Drawing.dll.config','System.Drawing.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'ICSharpCode.SharpZipLib', '2.6.0.0__1b03e6acf1164f73'):['ICSharpCode.SharpZipLib.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Posix', '2.0.0.0__0738eb9f132ed756'):['Mono.Posix.dll','Mono.Posix.dll.config','Mono.Posix.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System', '2.0.5.0__7cec85d7bea7798e'):['System.dll','System.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Security', '2.0.0.0__b03f5f7f11d50a3a'):['System.Security.dll','System.Security.dll.mdb',],
    os.path.join(basepath, 'etc', 'mono', '1.0'):['DefaultWsdlHelpGenerator.aspx','machine.config',],
    os.path.join(basepath, 'share', 'locale', 'ps', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Web.Abstractions', '3.5.0.0__31bf3856ad364e35'):['System.Web.Abstractions.dll','System.Web.Abstractions.dll.mdb',],
    os.path.join(basepath, 'share', 'locale', 'nl', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Xml.Linq', '3.5.0.0__b77a5c561934e089'):['System.Xml.Linq.dll','System.Xml.Linq.dll.mdb',],
    os.path.join(basepath, 'share', 'locale', 'bn', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'th', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'mr', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Web.Services', '1.0.5000.0__b03f5f7f11d50a3a'):['System.Web.Services.dll','System.Web.Services.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', '3.5'):['System.Web.Extensions.Design.dll',],
    os.path.join(basepath, 'lib'):['charset.alias','GNU.Gettext.dll','libasprintf.0.0.0.dylib','libasprintf.0.dylib','libasprintf.dylib','libatk-1.0.0.dylib','libatk-1.0.dylib','libatksharpglue-2.so','libcairo.2.dylib','libcairo.dylib','libexpat.1.5.2.dylib','libexpat.1.dylib','libexpat.dylib','libgailutil.18.0.1.dylib','libgailutil.18.dylib','libgailutil.dylib','libgdiplus.0.0.0.dylib','libgdiplus.0.dylib','libgdiplus.dylib','libgdk-quartz-2.0.0.1400.7.dylib','libgdk-quartz-2.0.0.dylib','libgdk-quartz-2.0.dylib','libgdk_pixbuf-2.0.0.1400.7.dylib','libgdk_pixbuf-2.0.0.dylib','libgdk_pixbuf-2.0.dylib','libgdksharpglue-2.so','libgettextlib-0.17.dylib','libgettextlib.dylib','libgettextpo.0.4.0.dylib','libgettextpo.0.dylib','libgettextpo.dylib','libgettextsrc-0.17.dylib','libgettextsrc.dylib','libgif.4.1.6.dylib','libgif.4.dylib','libgif.dylib','libgio-2.0.0.dylib','libgio-2.0.dylib','libglade-2.0.0.0.7.dylib','libglade-2.0.0.dylib','libglade-2.0.dylib','libgladesharpglue-2.so','libglib-2.0.0.dylib','libglib-2.0.dylib','libglibsharpglue-2.so','libgmodule-2.0.0.dylib','libgmodule-2.0.dylib','libgobject-2.0.0.dylib','libgobject-2.0.dylib','libgthread-2.0.0.dylib','libgthread-2.0.dylib','libgtk-quartz-2.0.0.1400.7.dylib','libgtk-quartz-2.0.0.dylib','libgtk-quartz-2.0.dylib','libgtksharpglue-2.so','libigemacintegration.0.0.0.dylib','libigemacintegration.0.dylib','libigemacintegration.dylib','libikvm-native.dylib','libintl.8.0.2.dylib','libintl.8.dylib','libintl.dylib','libjpeg.62.0.0.dylib','libjpeg.62.dylib','libjpeg.dylib','libmono-profiler-aot.0.0.0.dylib','libmono-profiler-aot.0.dylib','libmono-profiler-aot.dylib','libmono-profiler-cov.0.0.0.dylib','libmono-profiler-cov.0.dylib','libmono-profiler-cov.dylib','libmono.0.0.0.dylib','libmono.0.dylib','libmono.a','libmono.dylib','libMonoPosixHelper.dylib','libMonoSupportW.dylib','libpango-1.0.0.2203.1.dylib','libpango-1.0.0.dylib','libpango-1.0.dylib','libpangocairo-1.0.0.2203.1.dylib','libpangocairo-1.0.0.dylib','libpangocairo-1.0.dylib','libpangosharpglue-2.so','libpixman-1.0.14.0.dylib','libpixman-1.0.dylib','libpixman-1.dylib','libpng.3.dylib','libpng.dylib','libpng12.0.dylib','libpng12.dylib','libsqlite3.0.dylib','libsqlite3.dylib','libtiff.3.8.2.dylib','libtiff.3.dylib','libtiff.dylib','libtiffxx.3.8.2.dylib','libtiffxx.3.dylib','libtiffxx.dylib',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Messaging', '1.0.5000.0__b03f5f7f11d50a3a'):['Mono.Messaging.dll',],
    os.path.join(basepath, 'share', 'gtk-engines'):['clearlooks.xml','crux-engine.xml','glide.xml','hcengine.xml','industrial.xml','mist.xml','redmond95.xml','thinice.xml',],
    os.path.join(basepath, 'lib', 'IPCE', 'Lib', 'logging'):['__init__.py','config.py','handlers.py',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Cairo', '2.0.0.0__0738eb9f132ed756'):['Mono.Cairo.dll','Mono.Cairo.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'ByteFX.Data', '0.7.6.1__0738eb9f132ed756'):['ByteFX.Data.dll',],
    os.path.join(basepath, 'lib', 'gtk-2.0', '2.10.0', 'engines'):['libclearlooks.so',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'cocoa-sharp', '1.9.0.0__a2b5f5c17ce02f1d'):['cocoa-sharp.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.2.6.glade-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.6.config','policy.2.6.glade-sharp.dll',],
    os.path.join(basepath, 'share', 'locale', 'ja', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo','mcs.mo',],
    os.path.join(basepath, 'lib', 'IPCE', 'Lib', 'pyflakes'):['__init__.py','messages.py',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.GetOptions', '1.0.5000.0__0738eb9f132ed756'):['Mono.GetOptions.dll',],
    os.path.join(basepath, 'lib', 'xsp', 'test', '2.0', 'menu'):['index.aspx','menu1.aspx','menu2.aspx','stock_copy_24.png','stock_cut_24.png','stock_paste_24.png',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'ICSharpCode.SharpZipLib', '2.84.0.0__1b03e6acf1164f73'):['ICSharpCode.SharpZipLib.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'OpenSystem.C', '1.0.5000.0__b77a5c561934e089'):['OpenSystem.C.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.GetOptions', '2.0.0.0__0738eb9f132ed756'):['Mono.GetOptions.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Core', '2.0.5.0__7cec85d7bea7798e'):['System.Core.dll','System.Core.dll.mdb',],
    os.path.join(basepath, 'lib', 'xsp', '2.0'):['asp-state2.exe','asp-state2.exe.config','dbsessmgr2.exe','dbsessmgr2.exe.config',],
    os.path.join(basepath, 'share', 'themes', 'Clearlooks', 'gtk-2.0'):['gtkrc',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Windows.Forms', '2.0.0.0__b77a5c561934e089'):['System.Windows.Forms.dll','System.Windows.Forms.dll.config','System.Windows.Forms.dll.mdb',],
    os.path.join(basepath, 'lib', 'IPCE', 'Lib', 'fepy'):['__init__.py','ast.py','cipher.py','codecs_errors.py','encoding.py','fileobject.py','network.py','pickle.py','pth_support.py','regex.py',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'I18N.Rare', '2.0.0.0__0738eb9f132ed756'):['I18N.Rare.dll',],
    os.path.join(basepath, 'share', 'locale', 'mk', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'include', 'mono-1.0', 'mono', 'metadata'):['appdomain.h','assembly.h','attrdefs.h','blob.h','class.h','debug-helpers.h','debug-mono-symfile.h','environment.h','exception.h','image.h','loader.h','mempool.h','metadata.h','mono-config.h','mono-debug.h','mono-gc.h','object.h','opcodes.h','profiler.h','reflection.h','row-indexes.h','threads.h','tokentype.h','verify.h',],
    os.path.join(basepath, 'lib', 'monodoc', 'sources'):['cocoa-sharp.source','cocoa-sharp.tree','cocoa-sharp.zip','cs-errors.tree','cs-errors.zip','ecma334.tree','ecma334.zip','gtk-sharp-docs.source','gtk-sharp-docs.tree','gtk-sharp-docs.zip','lang-csharp.source','mono-file-formats.source','mono-file-formats.tree','mono-file-formats.zip','mono-tools.source','mono-tools.tree','mono-tools.zip','Mono.source','Mono.tree','Mono.zip','monoapi.source','monoapi.tree','monoapi.zip','netdocs.source','netdocs.tree','netdocs.zip','Novell.source','Novell.tree','Novell.zip',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Microsoft.VisualC', '7.0.5000.0__b03f5f7f11d50a3a'):['Microsoft.VisualC.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Security.Win32', '1.0.5000.0__0738eb9f132ed756'):['Mono.Security.Win32.dll',],
    os.path.join(basepath, 'share', 'locale', 'es', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo','mcs.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.ServiceModel', '3.0.0.0__b77a5c561934e089'):['System.ServiceModel.dll','System.ServiceModel.dll.mdb',],
    os.path.join(basepath, 'share', 'locale', 'ro', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'ka', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'xsp', 'test', '2.0'):['index.aspx',],
    os.path.join(basepath, 'share', 'locale', 'uz', 'LC_MESSAGES'):['gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Microsoft.Build.Framework', '2.0.0.0__b03f5f7f11d50a3a'):['Microsoft.Build.Framework.dll',],
    os.path.join(basepath, 'share', 'locale', 'ms', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'pl', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Xml.Linq', '2.0.5.0__31bf3856ad364e35'):['System.Xml.Linq.dll','System.Xml.Linq.dll.mdb',],
    os.path.join(basepath, 'lib', 'IPCE', 'Lib', 'Crypto', 'Hash'):['__init__.py','HMAC.py','MD5.py','SHA.py',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.2.4.atk-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.4.atk-sharp.dll','policy.2.4.config',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Drawing.Design', '1.0.5000.0__b03f5f7f11d50a3a'):['System.Drawing.Design.dll',],
    os.path.join(basepath, 'share', 'mono-1.0', 'mono', 'cil'):['cil-opcodes.xml',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.C5', '1.0.0.0__ba07f434b1c35cbd'):['Mono.C5.dll','Mono.C5.dll.mdb',],
    os.path.join(basepath, 'lib', 'IPCE', 'Lib', 'email'):['__init__.py','_parseaddr.py','base64MIME.py','Charset.py','Encoders.py','Errors.py','FeedParser.py','Generator.py','Header.py','Iterators.py','Message.py','MIMEAudio.py','MIMEBase.py','MIMEImage.py','MIMEMessage.py','MIMEMultipart.py','MIMENonMultipart.py','MIMEText.py','Parser.py','quopriMIME.py','Utils.py',],
    os.path.join(basepath, 'lib', 'pkgconfig'):['cecil.pc','cocoa-sharp.pc','dotnet.pc','dotnet35.pc','glade-sharp-2.0.pc','glib-sharp-2.0.pc','gtk-sharp-2.0.pc','mono-cairo.pc','mono-lineeditor.pc','mono-nunit.pc','mono-options.pc','mono.pc','mono.web.pc','monodoc.pc','smcs.pc','system.web.extensions.design_1.0.pc','system.web.extensions_1.0.pc','wcf.pc','webkit-sharp.pc',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.2.4.glade-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.4.config','policy.2.4.glade-sharp.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Accessibility', '1.0.5000.0__b03f5f7f11d50a3a'):['Accessibility.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'cscompmgd', '8.0.0.0__b03f5f7f11d50a3a'):['cscompmgd.dll',],
    os.path.join(basepath, 'share', 'locale', 'bg', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Runtime.Serialization.Formatters.Soap', '2.0.0.0__b03f5f7f11d50a3a'):['System.Runtime.Serialization.Formatters.Soap.dll','System.Runtime.Serialization.Formatters.Soap.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'PEAPI', '2.0.0.0__0738eb9f132ed756'):['PEAPI.dll',],
    os.path.join(basepath, 'share', 'locale', 'sv', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'li', 'LC_MESSAGES'):['gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Addins.Setup', '0.4.0.0__0738eb9f132ed756'):['Mono.Addins.Setup.dll','Mono.Addins.Setup.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Boo.Lang.Interpreter', '2.0.9.1__32c39770e9a21a67'):['Boo.Lang.Interpreter.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'mono-service', '2.0.0.0__0738eb9f132ed756'):['mono-service.exe',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Npgsql', '2.0.0.0__5d8b90d52f46fda7'):['Npgsql.dll',],
    os.path.join(basepath, 'lib', 'gtk-2.0', '2.10.0', 'immodules'):['im-am-et.so','im-cedilla.so','im-cyrillic-translit.so','im-inuktitut.so','im-ipa.so','im-multipress.so','im-thai.so','im-ti-er.so','im-ti-et.so','im-viqr.so',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'xsp', '2.4.2.0__0738eb9f132ed756'):['xsp.exe','xsp.exe.mdb',],
    os.path.join(basepath, 'share', 'locale', 'gl', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'NAnt', 'bin', 'lib', 'mono', '2.0'):['NDoc.Core.dll','NDoc.Documenter.Msdn.dll','NDoc.ExtendedUI.dll','nunit.core.dll','nunit.framework.dll','nunit.util.dll',],
    os.path.join(basepath, 'share', 'locale', 'el', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'xsp', 'test', '1.1', 'webservice'):['CompressExtension.cs','ConverterService.asmx','index.aspx','ServiceClient.exe.config','TestService.asmx',],
    os.path.join(basepath, 'lib', 'IPCE', 'Lib', 'email', 'test'):['__init__.py','test_email.py','test_email_codecs.py','test_email_torture.py',],
    os.path.join(basepath, 'lib', 'IPCE', 'ipy2'):['ipy.exe','ipyw.exe','IronPython.dll','IronPython.Modules.dll','IronPythonTest.dll','Microsoft.Scripting.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Runtime.Remoting', '1.0.5000.0__b77a5c561934e089'):['System.Runtime.Remoting.dll','System.Runtime.Remoting.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Data.Sqlite', '1.0.5000.0__0738eb9f132ed756'):['Mono.Data.Sqlite.dll','Mono.Data.Sqlite.dll.mdb',],
    os.path.join(basepath, 'share', 'locale', 'br', 'LC_MESSAGES'):['gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.2.8.atk-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.8.atk-sharp.dll','policy.2.8.config',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Http', '1.0.5000.0__0738eb9f132ed756'):['Mono.Http.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Runtime.Serialization', '3.0.0.0__b77a5c561934e089'):['System.Runtime.Serialization.dll','System.Runtime.Serialization.dll.mdb',],
    os.path.join(basepath, 'share', 'NAnt', 'bin'):['log4net.dll','NAnt.CompressionTasks.dll','NAnt.CompressionTasks.xml','NAnt.Core.dll','NAnt.Core.xml','NAnt.DotNetTasks.dll','NAnt.DotNetTasks.xml','NAnt.exe','NAnt.exe.config','NAnt.NUnit.dll','NAnt.NUnit.xml','NAnt.NUnit1Tasks.dll','NAnt.NUnit1Tasks.xml','NAnt.NUnit2Tasks.dll','NAnt.NUnit2Tasks.xml','NAnt.SourceControlTasks.dll','NAnt.SourceControlTasks.xml','NAnt.VisualCppTasks.dll','NAnt.VisualCppTasks.xml','NAnt.VSNetTasks.dll','NAnt.VSNetTasks.xml','NAnt.Win32Tasks.dll','NAnt.Win32Tasks.xml','NAnt.xml','scvs.exe',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'FirebirdSql.Data.Firebird', '1.7.1.0__0706f5520aae4ff4'):['FirebirdSql.Data.Firebird.dll',],
    os.path.join(basepath, 'share', 'locale', 'mn', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.2.8.gdk-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.8.config','policy.2.8.gdk-sharp.dll',],
    os.path.join(basepath, 'lib', 'boo'):['booc.exe','booc.exe.config','booc.rsp','booi.exe','booi.exe.config','booish.exe','booish.exe.config',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Data.TdsClient', '1.0.5000.0__0738eb9f132ed756'):['Mono.Data.TdsClient.dll','Mono.Data.TdsClient.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Web.Services', '2.0.0.0__b03f5f7f11d50a3a'):['System.Web.Services.dll','System.Web.Services.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.ServiceProcess', '1.0.5000.0__b03f5f7f11d50a3a'):['System.ServiceProcess.dll',],
    os.path.join(basepath, 'share', 'locale', 'ur', 'LC_MESSAGES'):['gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'gu', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'IPCE', 'Lib', 'encodings'):['__init__.py','aliases.py','base64_codec.py','charmap.py','hex_codec.py','rot_13.py','uu_codec.py','zlib_codec.py',],
    os.path.join(basepath):['env.csh','env.sh',],
    os.path.join(basepath, 'include', 'mono-1.0', 'mono', 'cil'):['opcode.def',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'glade-sharp', '2.12.0.0__35e10195dab3c99f'):['glade-sharp.dll','glade-sharp.dll.config',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'RabbitMQ.Client', '1.0.5000.0__b03f5f7f11d50a3a'):['RabbitMQ.Client.dll',],
    os.path.join(basepath, 'share', 'locale', 'sl', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'man', 'man1'):['al.1','asp-state.1.gz','cert2spc.1','certmgr.1','chktrust.1','cilc.1','csharp.1','dbsessmgr.1.gz','disco.1','dtd2xsd.1','envsubst.1','fastcgi-mono-server.1.gz','gacutil.1','gdk-pixbuf-query-loaders.1','genxs.1','gtk-update-icon-cache.1','httpcfg.1','ilasm.1','jay.1','macpack.1','makecert.1','mautil.1.gz','mconfig.1','mcs.1','mdassembler.1','mdoc-assemble.1','mdoc-export-html.1','mdoc-export-msxdoc.1','mdoc-update.1','mdoc-validate.1','mdoc.1','mdvalidater.1','mint.1','mkbundle.1','mod-mono-server.1.gz','mono-asp-apps.1.gz','mono-cil-strip.1','mono-service.1','mono-shlib-cop.1','mono-xmltool.1','mono.1','monodis.1','monodocer.1','monodocs2html.1','monolinker.1','monop.1','monostyle.1','mozroots.1','pango-querymodules.1','permview.1','pkg-config.1','prj2make.1','resgen.1','secutil.1','setreg.1','sgen.1','signcode.1','sn.1','soapsuds.1','sqlsharp.1','vbnc.1.gz','wsdl.1','xgettext.1','xsd.1','xsp.1.gz',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Web.Extensions.Design', '3.5.0.0__31bf3856ad364e35'):['System.Web.Extensions.Design.dll','System.Web.Extensions.Design.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'glib-sharp', '2.12.0.0__35e10195dab3c99f'):['glib-sharp.dll','glib-sharp.dll.config',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.EnterpriseServices', '1.0.5000.0__b03f5f7f11d50a3a'):['System.EnterpriseServices.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'gtk-sharp', '2.12.0.0__35e10195dab3c99f'):['gtk-sharp.dll','gtk-sharp.dll.config',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'I18N.CJK', '1.0.5000.0__0738eb9f132ed756'):['I18N.CJK.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'mod-mono-server', '2.4.2.0__0738eb9f132ed756'):['mod-mono-server.exe','mod-mono-server.exe.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.2.10.gdk-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.10.config','policy.2.10.gdk-sharp.dll',],
    os.path.join(basepath, 'share', 'locale', 'ga', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'ang', 'LC_MESSAGES'):['gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'cs', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'xsp', 'test', '1.1', 'handlers'):['async.ashx','chunked.ashx','empty.ashx','index.aspx','monodoc.ashx','webhandler.ashx',],
    os.path.join(basepath, 'share', 'locale', 'zh_CN', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'kn', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'fr', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'nunit.framework.extensions', '2.4.8.0__96d09a1eb7f44a77'):['nunit.framework.extensions.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Data', '1.0.5000.0__b77a5c561934e089'):['System.Data.dll','System.Data.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Net', '2.0.5.0__7cec85d7bea7798e'):['System.Net.dll','System.Net.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Messaging.RabbitMQ', '1.0.5000.0__b03f5f7f11d50a3a'):['Mono.Messaging.RabbitMQ.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Web.Extensions', '1.0.61025.0__31bf3856ad364e35'):['System.Web.Extensions.dll','System.Web.Extensions.dll.mdb',],
    os.path.join(basepath, 'lib', 'IPCE', 'Lib', 'Crypto', 'Cipher'):['__init__.py',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Windows.Forms', '1.0.5000.0__b77a5c561934e089'):['System.Windows.Forms.dll','System.Windows.Forms.dll.config','System.Windows.Forms.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Web.DynamicData', '3.5.0.0__31bf3856ad364e35'):['System.Web.DynamicData.dll','System.Web.DynamicData.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'nunit-console-runner', '2.4.8.0__96d09a1eb7f44a77'):['nunit-console-runner.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Simd', '2.0.0.0__0738eb9f132ed756'):['Mono.Simd.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System', '1.0.5000.0__b77a5c561934e089'):['System.dll','System.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.2.6.atk-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.6.atk-sharp.dll','policy.2.6.config',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.2.6.gdk-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.6.config','policy.2.6.gdk-sharp.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Addins.CecilReflector', '0.4.0.0__0738eb9f132ed756'):['Mono.Addins.CecilReflector.dll','Mono.Addins.CecilReflector.dll.mdb',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Data.Tds', '1.0.5000.0__0738eb9f132ed756'):['Mono.Data.Tds.dll','Mono.Data.Tds.dll.mdb',],
    os.path.join(basepath, 'share', 'locale', 'en_GB', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'share', 'locale', 'rw', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Design', '2.0.0.0__b03f5f7f11d50a3a'):['System.Design.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.2.10.glib-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.10.config','policy.2.10.glib-sharp.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'nunit.mocks', '2.4.8.0__96d09a1eb7f44a77'):['nunit.mocks.dll',],
    os.path.join(basepath, 'share', 'locale', 'nso', 'LC_MESSAGES'):['gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.CompilerServices.SymbolWriter', '2.0.0.0__0738eb9f132ed756'):['Mono.CompilerServices.SymbolWriter.dll','Mono.CompilerServices.SymbolWriter.dll.mdb',],
    os.path.join(basepath, 'lib', 'xsp', 'test', '2.0', 'treeview'):['index.aspx','populate-on-demand.aspx','populate.cs','treeview-databound.aspx','treeview.aspx',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'CustomMarshalers', '1.0.5000.0__b03f5f7f11d50a3a'):['CustomMarshalers.dll',],
    os.path.join(basepath, 'lib', 'IPCE', 'Lib', 'Crypto', 'Util', 'test'):['prime_speed.py',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Http', '2.0.0.0__0738eb9f132ed756'):['Mono.Http.dll',],
    os.path.join(basepath, 'lib', 'mono', '2.0', 'MSBuild'):['Microsoft.Build.CommonTypes.xsd','Microsoft.Build.Core.xsd',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Web', '2.0.0.0__0738eb9f132ed756'):['Mono.Web.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Microsoft.Build.Tasks', '2.0.0.0__b03f5f7f11d50a3a'):['Microsoft.Build.Tasks.dll',],
    os.path.join(basepath, 'etc', 'gtk-2.0'):['gdk-pixbuf.loaders','gtkrc','im-multipress.conf',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'System.Xml', '1.0.5000.0__b77a5c561934e089'):['System.Xml.dll','System.Xml.dll.mdb',],
    os.path.join(basepath, 'share', 'jay'):['ACKNOWLEDGEMENTS','NEW_FEATURES','NOTES','README','README.jay','skeleton','skeleton.cs',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.2.10.gtk-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.10.config','policy.2.10.gtk-sharp.dll',],
    os.path.join(basepath, 'lib', 'mono', 'cocoa-sharp'):['cocoa-sharp.dll','webkit-sharp.dll',],
    os.path.join(basepath, 'lib', 'mono', 'compat-2.0'):['ICSharpCode.SharpZipLib.dll','System.Web.Extensions.Design.dll','System.Web.Extensions.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.2.8.gtk-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.8.config','policy.2.8.gtk-sharp.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.2.4.pango-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.4.config','policy.2.4.pango-sharp.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.CSharp', '2.1.0.0__0738eb9f132ed756'):['Mono.CSharp.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.0.2.Mono.Addins.Gui', '0.0.0.0__0738eb9f132ed756'):['policy.0.2.config','policy.0.2.Mono.Addins.Gui.dll',],
    os.path.join(basepath, 'share', 'locale', 'cy', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'include', 'mono-1.0', 'mono', 'jit'):['jit.h',],
    os.path.join(basepath, 'share', 'locale', 'ru', 'LC_MESSAGES'):['glib20.mo','gtk20-properties.mo','gtk20.mo',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Messaging', '2.0.0.0__b03f5f7f11d50a3a'):['Mono.Messaging.dll',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'Mono.Data.SqliteClient', '2.0.0.0__0738eb9f132ed756'):['Mono.Data.SqliteClient.dll','Mono.Data.SqliteClient.dll.mdb',],
    os.path.join(basepath, 'etc', 'mono'):['browscap.ini','config',],
    os.path.join(basepath, 'lib', 'mono', 'gac', 'policy.0.3.Mono.Addins', '0.0.0.0__0738eb9f132ed756'):['policy.0.3.config','policy.0.3.Mono.Addins.dll',],
}

symlinks = {
    os.path.join(basepath, 'include'):['png.h','pngconf.h',],
}

