pkgconfiglist = [
    'boo',
    'cecil',
    'cocoa-sharp',
    'dotnet',
    'dotnet35',
    'glade-sharp-2.0',
    'glib-sharp-2.0',
    'gtk-sharp-2.0',
    'mono',
    'mono-addins',
    'mono-addins-gui',
    'mono-addins-setup',
    'mono-cairo',
    'mono-lineeditor',
    'mono-nunit',
    'mono-options',
    'mono.web',
    'monodoc',
    'smcs',
    'system.web.extensions.design_1.0',
    'system.web.extensions_1.0',
    'wcf',
    'webkit-sharp',
    'xsp',
    'xsp-2',
]

