
import os
basepath = '/usr/lib/mono'

files = {
    os.path.join(basepath, 'gac', 'PEAPI', '1.0.5000.0__0738eb9f132ed756'):['PEAPI.dll.mdb','PEAPI.dll',],
    os.path.join(basepath, 'evolution-sharp'):['evolution-sharp.dll',],
    os.path.join(basepath, 'gac', 'CustomMarshalers', '2.0.0.0__b03f5f7f11d50a3a'):['CustomMarshalers.dll','CustomMarshalers.dll.mdb',],
    os.path.join(basepath, 'gac', 'System.Security', '2.0.0.0__b03f5f7f11d50a3a'):['System.Security.dll.mdb','System.Security.dll',],
    os.path.join(basepath, 'gac', 'Boo.Lang.Parser', '2.0.0.0__32c39770e9a21a67'):['Boo.Lang.Parser.dll','Boo.Lang.Parser.dll.mdb',],
    os.path.join(basepath, 'gnomedesktop-sharp-2.20'):['gnomedesktop-sharp.dll',],
    os.path.join(basepath, '3.5'):['System.Web.Extensions.Design.dll',],
    os.path.join(basepath, 'gac', 'Mono.Messaging', '2.0.0.0__b03f5f7f11d50a3a'):['Mono.Messaging.dll.mdb','Mono.Messaging.dll',],
    os.path.join(basepath, 'gac', 'System.Web.Routing', '3.5.0.0__31bf3856ad364e35'):['System.Web.Routing.dll.mdb','System.Web.Routing.dll',],
    os.path.join(basepath, 'gac', 'gnomedesktop-sharp', '2.20.0.0__35e10195dab3c99f'):['gnomedesktop-sharp.dll.config','gnomedesktop-sharp.dll.mdb','gnomedesktop-sharp.dll',],
    os.path.join(basepath, 'gac', 'policy.2.10.gdk-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.10.gdk-sharp.dll','policy.2.10.config',],
    os.path.join(basepath, 'gac', 'I18N.Other', '2.0.0.0__0738eb9f132ed756'):['I18N.Other.dll.mdb','I18N.Other.dll',],
    os.path.join(basepath, 'gac', 'System.Drawing', '1.0.5000.0__b03f5f7f11d50a3a'):['System.Drawing.dll.mdb','System.Drawing.dll',],
    os.path.join(basepath, '1.0'):['signcode.exe','installvst.exe.mdb','Microsoft.Vsa.dll','nunit-console.exe.config','OpenSystem.C.dll','System.Messaging.dll','Mono.Cairo.dll','al.exe','Mono.Http.dll','Npgsql.dll','ICSharpCode.SharpZipLib.dll','makecert.exe','mkbundle.exe.mdb','System.Management.dll','genxs.exe.mdb','mono-cil-strip.exe.mdb','cscompmgd.dll','ilasm.exe.mdb','sn.exe','mkbundle.exe','permview.exe.mdb','nunit.core.interfaces.dll','Mono.Data.SqliteClient.dll','System.Xml.dll','nunit.mocks.dll','mod-mono-server.exe','Accessibility.dll','dtd2rng.exe','caspol.exe','System.Design.dll','Commons.Xml.Relaxng.dll','cert2spc.exe','nunit.util.dll','ictool.exe.mdb','System.Configuration.Install.dll','makecert.exe.mdb','CustomMarshalers.dll','Microsoft.VisualBasic.dll','mcs.exe.config','disco.exe','Mono.Messaging.dll','ictool.exe','Mono.Messaging.RabbitMQ.dll','wsdl.exe','setreg.exe','ByteFX.Data.dll','mcs.exe','mono-xmltool.exe.mdb','dtd2rng.exe.mdb','Mono.Posix.dll','mono-service.exe.mdb','secutil.exe.mdb','xsd.exe','soapsuds.exe','RabbitMQ.Client.dll','Mono.Data.SybaseClient.dll','Mono.Data.TdsClient.dll','macpack.exe.mdb','certmgr.exe','I18N.dll','nunit-console-runner.dll','I18N.Other.dll','prj2make.exe','mono-xmltool.exe','System.ServiceProcess.dll','Novell.Directory.Ldap.dll','dtd2xsd.exe','mono-service.exe','Mono.GetOptions.dll','Mono.WebServer.dll','wsdl.exe.mdb','mscorlib.dll.mdb','certmgr.exe.mdb','disco.exe.mdb','gacutil.exe','mod.exe.mdb','I18N.West.dll','genxs.exe','Mono.CompilerServices.SymbolWriter.dll','sn.exe.mdb','ilasm.exe','nunit-console.exe','I18N.CJK.dll','fastcgi-mono-server.exe','System.Data.dll','mscorlib.dll','I18N.MidEast.dll','xsd.exe.mdb','mozroots.exe','mcs.exe.mdb','FirebirdSql.Data.Firebird.dll','monop.exe.mdb','al.exe.mdb','monop.exe','Mono.Data.dll','Mono.Security.dll','chktrust.exe.mdb','I18N.Rare.dll','Mono.Data.Sqlite.dll','caspol.exe.mdb','System.Runtime.Serialization.Formatters.Soap.dll','Mono.Data.Tds.dll','System.Web.dll','System.Runtime.Remoting.dll','System.Data.OracleClient.dll','resgen.exe.mdb','prj2make.exe.mdb','monolinker.exe','nunit.framework.extensions.dll','cert2spc.exe.mdb','nunit.core.extensions.dll','System.EnterpriseServices.dll','System.Drawing.dll','gacutil.exe.mdb','mod.exe','Mono.WebBrowser.dll','soapsuds.exe.mdb','chktrust.exe','installvst.exe','monolinker.exe.mdb','PEAPI.dll','signcode.exe.mdb','System.Windows.Forms.dll','gasnview.exe','nunit-console.exe.mdb','System.DirectoryServices.dll','Microsoft.VisualC.dll','macpack.exe','nunit.core.dll','mozroots.exe.mdb','installutil.exe','System.Drawing.Design.dll','System.Web.Services.dll','installutil.exe.mdb','permview.exe','mono-cil-strip.exe','resgen.exe','System.Security.dll','secutil.exe','System.dll','xsp.exe','nunit.framework.dll','dtd2xsd.exe.mdb','setreg.exe.mdb',],
    os.path.join(basepath, 'gac', 'System.Drawing', '2.0.0.0__b03f5f7f11d50a3a'):['System.Drawing.dll.mdb','System.Drawing.dll',],
    os.path.join(basepath, 'gac', 'I18N.Other', '1.0.5000.0__0738eb9f132ed756'):['I18N.Other.dll.mdb','I18N.Other.dll',],
    os.path.join(basepath, 'gac', 'System.Data.Linq', '3.5.0.0__b77a5c561934e089'):['System.Data.Linq.dll.mdb','System.Data.Linq.dll',],
    os.path.join(basepath, 'gac', 'System.Messaging', '2.0.0.0__b03f5f7f11d50a3a'):['System.Messaging.dll','System.Messaging.dll.mdb',],
    os.path.join(basepath, 'gac', 'policy.2.4.gtk-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.4.gtk-sharp.dll','policy.2.4.config',],
    os.path.join(basepath, 'gac', 'policy.2.4.gtk-dotnet', '0.0.0.0__35e10195dab3c99f'):['policy.2.4.gtk-dotnet.dll','policy.2.4.config',],
    os.path.join(basepath, 'gac', 'IKVM.OpenJDK.ClassLibrary', '0.38.0.4__13235d27fcbfff58'):['IKVM.OpenJDK.ClassLibrary.dll',],
    os.path.join(basepath, 'gac', 'Mono.GetOptions', '1.0.5000.0__0738eb9f132ed756'):['Mono.GetOptions.dll','Mono.GetOptions.dll.mdb',],
    os.path.join(basepath, 'gac', 'policy.3.0.Mono.Zeroconf', '0.0.0.0__e60c4f4a95e1099e'):['policy.3.0.Mono.Zeroconf.dll','policy.3.0.config',],
    os.path.join(basepath, 'gac', 'System.EnterpriseServices', '2.0.0.0__b03f5f7f11d50a3a'):['System.EnterpriseServices.dll.mdb','System.EnterpriseServices.dll',],
    os.path.join(basepath, 'gac', 'PEAPI', '2.0.0.0__0738eb9f132ed756'):['PEAPI.dll.mdb','PEAPI.dll',],
    os.path.join(basepath, 'gac', 'ICSharpCode.SharpZipLib', '2.6.0.0__1b03e6acf1164f73'):['ICSharpCode.SharpZipLib.dll','ICSharpCode.SharpZipLib.dll.mdb',],
    os.path.join(basepath, 'gac', 'I18N.Rare', '1.0.5000.0__0738eb9f132ed756'):['I18N.Rare.dll.mdb','I18N.Rare.dll',],
    os.path.join(basepath, 'gac', 'ByteFX.Data', '0.7.6.2__0738eb9f132ed756'):['ByteFX.Data.dll.mdb','ByteFX.Data.dll',],
    os.path.join(basepath, 'gac', 'System.Security', '1.0.5000.0__b03f5f7f11d50a3a'):['System.Security.dll.mdb','System.Security.dll',],
    os.path.join(basepath, 'gac', 'FirebirdSql.Data.Firebird', '1.7.1.0__0706f5520aae4ff4'):['FirebirdSql.Data.Firebird.dll','FirebirdSql.Data.Firebird.dll.mdb',],
    os.path.join(basepath, 'gac', 'policy.2.8.glade-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.8.glade-sharp.dll','policy.2.8.config',],
    os.path.join(basepath, 'gac', 'fastcgi-mono-server2', '2.4.0.0__0738eb9f132ed756'):['fastcgi-mono-server2.exe','fastcgi-mono-server2.exe.mdb',],
    os.path.join(basepath, 'gac', 'System.Xml.Linq', '2.0.5.0__31bf3856ad364e35'):['System.Xml.Linq.dll','System.Xml.Linq.dll.mdb',],
    os.path.join(basepath, 'mono-addins'):['Mono.Addins.dll','Mono.Addins.CecilReflector.dll','Mono.Addins.Setup.dll','Mono.Addins.Gui.dll','mautil.exe',],
    os.path.join(basepath, 'gac', 'System.Web.Abstractions', '3.5.0.0__31bf3856ad364e35'):['System.Web.Abstractions.dll','System.Web.Abstractions.dll.mdb',],
    os.path.join(basepath, 'gac', 'policy.0.3.Mono.Addins.Gui', '0.0.0.0__0738eb9f132ed756'):['policy.0.3.config','policy.0.3.Mono.Addins.Gui.dll',],
    os.path.join(basepath, 'gac', 'Mono.WebBrowser', '0.5.0.0__0738eb9f132ed756'):['Mono.WebBrowser.dll.mdb','Mono.WebBrowser.dll',],
    os.path.join(basepath, 'gac', 'mono-service', '1.0.5000.0__0738eb9f132ed756'):['mono-service.exe.mdb','mono-service.exe',],
    os.path.join(basepath, 'gac', 'I18N.West', '1.0.5000.0__0738eb9f132ed756'):['I18N.West.dll.mdb','I18N.West.dll',],
    os.path.join(basepath, 'gac', 'System.DirectoryServices', '2.0.0.0__b03f5f7f11d50a3a'):['System.DirectoryServices.dll.mdb','System.DirectoryServices.dll',],
    os.path.join(basepath, 'gac', 'policy.2.10.pango-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.10.pango-sharp.dll','policy.2.10.config',],
    os.path.join(basepath, 'gac', 'System.Runtime.Serialization.Formatters.Soap', '2.0.0.0__b03f5f7f11d50a3a'):['System.Runtime.Serialization.Formatters.Soap.dll','System.Runtime.Serialization.Formatters.Soap.dll.mdb',],
    os.path.join(basepath, 'gac', 'glib-sharp', '2.12.0.0__35e10195dab3c99f'):['glib-sharp.dll','glib-sharp.dll.mdb','glib-sharp.dll.config',],
    os.path.join(basepath, 'gac', 'Microsoft.Build.Framework', '2.0.0.0__b03f5f7f11d50a3a'):['Microsoft.Build.Framework.dll.mdb','Microsoft.Build.Framework.dll',],
    os.path.join(basepath, 'gac', 'System.Drawing.Design', '1.0.5000.0__b03f5f7f11d50a3a'):['System.Drawing.Design.dll.mdb','System.Drawing.Design.dll',],
    os.path.join(basepath, 'gac', 'Microsoft.Build.Tasks', '2.0.0.0__b03f5f7f11d50a3a'):['Microsoft.Build.Tasks.dll.mdb','Microsoft.Build.Tasks.dll',],
    os.path.join(basepath, 'gnome-keyring-sharp-1.0'):['Gnome.Keyring.dll',],
    os.path.join(basepath, 'gac', 'gconf-sharp', '2.24.0.0__35e10195dab3c99f'):['gconf-sharp.dll.mdb','gconf-sharp.dll','gconf-sharp.dll.config',],
    os.path.join(basepath, 'gac', 'Mono.Http', '2.0.0.0__0738eb9f132ed756'):['Mono.Http.dll','Mono.Http.dll.mdb',],
    os.path.join(basepath, 'gac', 'Boo.Lang.Useful', '2.0.0.0__32c39770e9a21a67'):['Boo.Lang.Useful.dll.mdb','Boo.Lang.Useful.dll',],
    os.path.join(basepath, 'taglib-sharp'):['taglib-sharp.dll',],
    os.path.join(basepath, 'gac', 'System.Runtime.Remoting', '1.0.5000.0__b77a5c561934e089'):['System.Runtime.Remoting.dll','System.Runtime.Remoting.dll.mdb',],
    os.path.join(basepath, 'gac', 'policy.2.10.glade-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.10.glade-sharp.dll','policy.2.10.config',],
    os.path.join(basepath, 'gac', 'Accessibility', '1.0.5000.0__b03f5f7f11d50a3a'):['Accessibility.dll','Accessibility.dll.mdb',],
    os.path.join(basepath, 'gac', 'cscompmgd', '8.0.0.0__b03f5f7f11d50a3a'):['cscompmgd.dll','cscompmgd.dll.mdb',],
    os.path.join(basepath, 'gac', 'policy.2.4.pango-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.4.pango-sharp.dll','policy.2.4.config',],
    os.path.join(basepath, 'gac', 'Microsoft.VisualBasic', '8.0.0.0__b03f5f7f11d50a3a'):['Microsoft.VisualBasic.dll','Microsoft.VisualBasic.dll.mdb',],
    os.path.join(basepath, 'gac', 'Mono.CompilerServices.SymbolWriter', '2.0.0.0__0738eb9f132ed756'):['Mono.CompilerServices.SymbolWriter.dll.mdb','Mono.CompilerServices.SymbolWriter.dll',],
    os.path.join(basepath, 'gac', 'Mono.Simd', '2.0.0.0__0738eb9f132ed756'):['Mono.Simd.dll.mdb','Mono.Simd.dll',],
    os.path.join(basepath, 'gac', 'gnome-print-sharp', '2.18.0.0__35e10195dab3c99f'):['gnome-print-sharp.dll.config','gnome-print-sharp.dll','gnome-print-sharp.dll.mdb',],
    os.path.join(basepath, 'gac', 'System.Data', '2.0.0.0__b77a5c561934e089'):['System.Data.dll.mdb','System.Data.dll',],
    os.path.join(basepath, 'gac', 'policy.2.6.gtk-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.6.gtk-sharp.dll','policy.2.6.config',],
    os.path.join(basepath, 'gtkhtml-sharp-3.14'):['gtkhtml-sharp.dll',],
    os.path.join(basepath, 'gac', 'cscompmgd', '7.0.5000.0__b03f5f7f11d50a3a'):['cscompmgd.dll','cscompmgd.dll.mdb',],
    os.path.join(basepath, 'gac', 'System.DirectoryServices', '1.0.5000.0__b03f5f7f11d50a3a'):['System.DirectoryServices.dll.mdb','System.DirectoryServices.dll',],
    os.path.join(basepath, 'gac', 'gtk-sharp', '2.12.0.0__35e10195dab3c99f'):['gtk-sharp.dll','gtk-sharp.dll.mdb','gtk-sharp.dll.config',],
    os.path.join(basepath, 'gac', 'policy.2.8.gtk-dotnet', '0.0.0.0__35e10195dab3c99f'):['policy.2.8.config','policy.2.8.gtk-dotnet.dll',],
    os.path.join(basepath, 'ndesk-dbus-glib-1.0'):['NDesk.DBus.GLib.dll',],
    os.path.join(basepath, 'gac', 'System', '1.0.5000.0__b77a5c561934e089'):['System.dll.mdb','System.dll',],
    os.path.join(basepath, 'gac', 'dbus-sharp', '0.60.0.0__9eef2692033670f5'):['dbus-sharp.dll.mdb','dbus-sharp.dll','dbus-sharp.dll.config',],
    os.path.join(basepath, 'gac', 'Boo.Lang.Interpreter', '2.0.0.0__32c39770e9a21a67'):['Boo.Lang.Interpreter.dll','Boo.Lang.Interpreter.dll.mdb',],
    os.path.join(basepath, 'gac', 'Mono.Data.SqliteClient', '2.0.0.0__0738eb9f132ed756'):['Mono.Data.SqliteClient.dll','Mono.Data.SqliteClient.dll.mdb',],
    os.path.join(basepath, 'gac', 'System.Web.Extensions.Design', '3.5.0.0__31bf3856ad364e35'):['System.Web.Extensions.Design.dll.mdb','System.Web.Extensions.Design.dll',],
    os.path.join(basepath, 'gac', 'System.Configuration.Install', '2.0.0.0__b03f5f7f11d50a3a'):['System.Configuration.Install.dll','System.Configuration.Install.dll.mdb',],
    os.path.join(basepath, 'gac', 'log4net', '1.2.10.0__200a2bd1219e83a8'):['log4net.dll',],
    os.path.join(basepath, 'gac', 'Mono.Data.TdsClient', '1.0.5000.0__0738eb9f132ed756'):['Mono.Data.TdsClient.dll','Mono.Data.TdsClient.dll.mdb',],
    os.path.join(basepath, 'gac', 'Commons.Xml.Relaxng', '2.0.0.0__0738eb9f132ed756'):['Commons.Xml.Relaxng.dll','Commons.Xml.Relaxng.dll.mdb',],
    os.path.join(basepath, 'gtk-sharp'):['gsf-sharp.dll',],
    os.path.join(basepath, 'gac', 'System.Web.Extensions.Design', '1.0.61025.0__31bf3856ad364e35'):['System.Web.Extensions.Design.dll.mdb','System.Web.Extensions.Design.dll',],
    os.path.join(basepath, 'gac', 'policy.2.6.glade-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.6.config','policy.2.6.glade-sharp.dll',],
    os.path.join(basepath, 'gac', 'nunit.util', '2.4.8.0__96d09a1eb7f44a77'):['nunit.util.dll','nunit.util.dll.mdb',],
    os.path.join(basepath, 'gac', 'Mono.Posix', '2.0.0.0__0738eb9f132ed756'):['Mono.Posix.dll.mdb','Mono.Posix.dll',],
    os.path.join(basepath, 'gac', 'policy.2.0.Mono.Zeroconf', '0.0.0.0__e60c4f4a95e1099e'):['policy.2.0.Mono.Zeroconf.dll','policy.2.0.config',],
    os.path.join(basepath, 'gac', 'policy.2.8.atk-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.8.atk-sharp.dll','policy.2.8.config',],
    os.path.join(basepath, 'gac', 'mono-service', '2.0.0.0__0738eb9f132ed756'):['mono-service.exe.mdb','mono-service.exe',],
    os.path.join(basepath, 'avahi-sharp'):['avahi-sharp.dll',],
    os.path.join(basepath, 'gac', 'nunit.core.extensions', '2.4.8.0__96d09a1eb7f44a77'):['nunit.core.extensions.dll.mdb','nunit.core.extensions.dll',],
    os.path.join(basepath, 'gac', 'Mono.Addins.Setup', '0.4.0.0__0738eb9f132ed756'):['Mono.Addins.Setup.dll','Mono.Addins.Setup.dll.mdb',],
    os.path.join(basepath, 'gac', 'atk-sharp', '2.12.0.0__35e10195dab3c99f'):['atk-sharp.dll.mdb','atk-sharp.dll','atk-sharp.dll.config',],
    os.path.join(basepath, 'notify-sharp'):['notify-sharp.dll',],
    os.path.join(basepath, 'gac', 'Mono.Cairo', '1.0.5000.0__0738eb9f132ed756'):['Mono.Cairo.dll','Mono.Cairo.dll.mdb',],
    os.path.join(basepath, 'gac', 'System.Web.Services', '1.0.5000.0__b03f5f7f11d50a3a'):['System.Web.Services.dll.mdb','System.Web.Services.dll',],
    os.path.join(basepath, 'gac', 'gnome-vfs-sharp', '2.24.0.0__35e10195dab3c99f'):['gnome-vfs-sharp.dll.config','gnome-vfs-sharp.dll','gnome-vfs-sharp.dll.mdb',],
    os.path.join(basepath, 'gac', 'Mono.Cecil.Mdb', '0.2.0.0__0738eb9f132ed756'):['Mono.Cecil.Mdb.dll.mdb','Mono.Cecil.Mdb.dll',],
    os.path.join(basepath, 'gac', 'ByteFX.Data', '0.7.6.1__0738eb9f132ed756'):['ByteFX.Data.dll.mdb','ByteFX.Data.dll',],
    os.path.join(basepath, 'gnome-print-sharp-2.18'):['gnome-print-sharp.dll',],
    os.path.join(basepath, 'gac', 'policy.0.3.Mono.Addins', '0.0.0.0__0738eb9f132ed756'):['policy.0.3.Mono.Addins.dll','policy.0.3.config',],
    os.path.join(basepath, 'gac', 'glade-sharp', '2.12.0.0__35e10195dab3c99f'):['glade-sharp.dll.config','glade-sharp.dll','glade-sharp.dll.mdb',],
    os.path.join(basepath, 'gac', 'gtksourceview-sharp', '1.0.0.2__35e10195dab3c99f'):['gtksourceview-sharp.dll','gtksourceview-sharp.dll.config',],
    os.path.join(basepath, 'monodoc'):['monodoc.dll',],
    os.path.join(basepath, 'gac', 'Mono.Data.Tds', '1.0.5000.0__0738eb9f132ed756'):['Mono.Data.Tds.dll','Mono.Data.Tds.dll.mdb',],
    os.path.join(basepath, 'gac', 'Mono.Addins.Gui', '0.4.0.0__0738eb9f132ed756'):['Mono.Addins.Gui.dll.mdb','Mono.Addins.Gui.dll',],
    os.path.join(basepath, 'gac', 'System.Data.OracleClient', '2.0.0.0__b77a5c561934e089'):['System.Data.OracleClient.dll.mdb','System.Data.OracleClient.dll',],
    os.path.join(basepath, 'gnome-panel-sharp-2.24'):['gnome-panel-sharp.dll',],
    os.path.join(basepath, 'gac', 'System.EnterpriseServices', '1.0.5000.0__b03f5f7f11d50a3a'):['System.EnterpriseServices.dll.mdb','System.EnterpriseServices.dll',],
    os.path.join(basepath, 'gac', 'NDesk.DBus', '1.0.0.0__f6716e4f9b2ed099'):['NDesk.DBus.dll.mdb','NDesk.DBus.dll',],
    os.path.join(basepath, 'gac', 'Commons.Xml.Relaxng', '1.0.5000.0__0738eb9f132ed756'):['Commons.Xml.Relaxng.dll','Commons.Xml.Relaxng.dll.mdb',],
    os.path.join(basepath, 'gac', 'Mono.Security', '2.0.0.0__0738eb9f132ed756'):['Mono.Security.dll.mdb','Mono.Security.dll',],
    os.path.join(basepath, 'gac', 'System', '2.0.0.0__b77a5c561934e089'):['System.dll.mdb','System.dll',],
    os.path.join(basepath, 'gac', 'System.Management', '1.0.5000.0__b03f5f7f11d50a3a'):['System.Management.dll','System.Management.dll.mdb',],
    os.path.join(basepath, 'gac', 'policy.0.3.Mono.Addins.CecilReflector', '0.0.0.0__0738eb9f132ed756'):['policy.0.3.config','policy.0.3.Mono.Addins.CecilReflector.dll',],
    os.path.join(basepath, 'gac', 'policy.2.10.gtk-dotnet', '0.0.0.0__35e10195dab3c99f'):['policy.2.10.config','policy.2.10.gtk-dotnet.dll',],
    os.path.join(basepath, 'gac', 'System.Design', '2.0.0.0__b03f5f7f11d50a3a'):['System.Design.dll.mdb','System.Design.dll',],
    os.path.join(basepath, 'gac', 'RabbitMQ.Client', '2.0.0.0__b03f5f7f11d50a3a'):['RabbitMQ.Client.dll.mdb','RabbitMQ.Client.dll',],
    os.path.join(basepath, 'ikvm'):['IKVM.AWT.WinForms.dll','IKVM.Runtime.dll','IKVM.OpenJDK.ClassLibrary.dll',],
    os.path.join(basepath, 'gac', 'gnome-panel-sharp', '2.24.0.0__35e10195dab3c99f'):['gnome-panel-sharp.dll','gnome-panel-sharp.dll.mdb','gnome-panel-sharp.dll.config',],
    os.path.join(basepath, 'gac', 'nunit.framework.extensions', '2.4.8.0__96d09a1eb7f44a77'):['nunit.framework.extensions.dll.mdb','nunit.framework.extensions.dll',],
    os.path.join(basepath, 'gac', 'Mono.CSharp', '2.1.0.0__0738eb9f132ed756'):['Mono.CSharp.dll',],
    os.path.join(basepath, 'gac', 'IKVM.AWT.WinForms', '0.38.0.4__13235d27fcbfff58'):['IKVM.AWT.WinForms.dll',],
    os.path.join(basepath, 'gac', 'policy.2.6.gtk-dotnet', '0.0.0.0__35e10195dab3c99f'):['policy.2.6.gtk-dotnet.dll','policy.2.6.config',],
    os.path.join(basepath, 'gac', 'System.Xml.Linq', '3.5.0.0__b77a5c561934e089'):['System.Xml.Linq.dll','System.Xml.Linq.dll.mdb',],
    os.path.join(basepath, 'gac', 'Microsoft.VisualC', '8.0.0.0__b03f5f7f11d50a3a'):['Microsoft.VisualC.dll.mdb','Microsoft.VisualC.dll',],
    os.path.join(basepath, 'gac', 'policy.1.0.Mono.Zeroconf', '0.0.0.0__e60c4f4a95e1099e'):['policy.1.0.config','policy.1.0.Mono.Zeroconf.dll',],
    os.path.join(basepath, 'gac', 'System.Web', '1.0.5000.0__b03f5f7f11d50a3a'):['System.Web.dll','System.Web.dll.mdb',],
    os.path.join(basepath, 'gac', 'Mono.Messaging.RabbitMQ', '1.0.5000.0__b03f5f7f11d50a3a'):['Mono.Messaging.RabbitMQ.dll.mdb','Mono.Messaging.RabbitMQ.dll',],
    os.path.join(basepath, '2.1'):['System.Xml.dll','smcs.exe.mdb','smcs.exe','mscorlib.dll.mdb','System.Net.dll','Mono.CompilerServices.SymbolWriter.dll','System.Xml.Linq.dll','mscorlib.dll','System.Core.dll','System.dll',],
    os.path.join(basepath, '2.0'):['Microsoft.Vsa.dll','nunit-console.exe.config','OpenSystem.C.dll','System.Messaging.dll','Mono.Cairo.dll','al.exe','Mono.Http.dll','Npgsql.dll','ICSharpCode.SharpZipLib.dll','sgen.exe.mdb','System.ComponentModel.DataAnnotations.dll','System.Data.DataSetExtensions.dll','mkbundle.exe.mdb','System.Management.dll','cscompmgd.dll','ilasm.exe.mdb','Mono.C5.dll','System.Web.Abstractions.dll','fastcgi-mono-server2.exe','mkbundle.exe','mono-shlib-cop.exe.config','nunit.core.interfaces.dll','Mono.Data.SqliteClient.dll','System.Xml.dll','gmcs.exe.config','mono-shlib-cop.exe.mdb','sgen.exe','nunit.mocks.dll','xsp2.exe','Microsoft.Common.tasks','Accessibility.dll','System.Design.dll','csharp.exe.mdb','Commons.Xml.Relaxng.dll','nunit.util.dll','System.Configuration.Install.dll','CustomMarshalers.dll','mdoc.exe.mdb','Microsoft.VisualBasic.dll','vbnc.exe.mdb','mdoc.exe','System.Data.Linq.dll','System.Web.Extensions.dll','Mono.Messaging.dll','Mono.Messaging.RabbitMQ.dll','wsdl.exe','ByteFX.Data.dll','xbuild.rsp','Microsoft.CSharp.targets','Mono.Posix.dll','Microsoft.Build.Engine.dll','mono-service.exe.mdb','xsd.exe','RabbitMQ.Client.dll','Mono.Data.SybaseClient.dll','Mono.Data.TdsClient.dll','csharp.exe','I18N.dll','nunit-console-runner.dll','I18N.Other.dll','mconfig.exe.mdb','mono-api-info.exe','System.ServiceProcess.dll','Novell.Directory.Ldap.dll','mono-service.exe','Mono.GetOptions.dll','System.Web.Extensions.Design.dll','wsdl.exe.mdb','mscorlib.dll.mdb','vbnc.rsp','gacutil.exe','Microsoft.Common.targets','Mono.CSharp.dll','I18N.West.dll','Mono.CompilerServices.SymbolWriter.dll','ilasm.exe','nunit-console.exe','Microsoft.VisualBasic.targets','I18N.CJK.dll','Microsoft.Build.Utilities.dll','httpcfg.exe.mdb','System.Xml.Linq.dll','System.Data.dll','mscorlib.dll','mod-mono-server2.exe','I18N.MidEast.dll','httpcfg.exe','xsd.exe.mdb','monop.exe.mdb','al.exe.mdb','monop.exe','Mono.Data.dll','Mono.WebServer2.dll','gmcs.exe.mdb','Mono.Security.dll','Mono.Simd.dll','System.Transactions.dll','I18N.Rare.dll','Mono.Data.Sqlite.dll','Microsoft.Build.Tasks.dll','Microsoft.Build.Framework.dll','System.Runtime.Serialization.Formatters.Soap.dll','Mono.Data.Tds.dll','System.Web.dll','gmcs.exe','xbuild.exe.mdb','System.Runtime.Remoting.dll','System.Data.OracleClient.dll','resgen.exe.mdb','nunit.framework.extensions.dll','nunit.core.extensions.dll','System.EnterpriseServices.dll','Microsoft.Build.xsd','System.Drawing.dll','gacutil.exe.mdb','System.Web.DynamicData.dll','Mono.WebBrowser.dll','System.Configuration.dll','xbuild.exe','PEAPI.dll','sqlsharp.exe','System.Core.dll','System.Windows.Forms.dll','nunit-console.exe.mdb','System.DirectoryServices.dll','System.Web.Routing.dll','mconfig.exe','Mono.Management.dll','Microsoft.VisualC.dll','nunit.core.dll','installutil.exe','System.Drawing.Design.dll','System.Web.Services.dll','installutil.exe.mdb','vbnc.exe','resgen.exe','System.Security.dll','System.dll','Mono.Web.dll','nunit.framework.dll','sqlsharp.exe.mdb','mono-shlib-cop.exe',],
    os.path.join(basepath, 'gac', 'Boo.Lang.CodeDom', '2.0.0.0__32c39770e9a21a67'):['Boo.Lang.CodeDom.dll.mdb','Boo.Lang.CodeDom.dll',],
    os.path.join(basepath, 'gac', 'CustomMarshalers', '1.0.5000.0__b03f5f7f11d50a3a'):['CustomMarshalers.dll','CustomMarshalers.dll.mdb',],
    os.path.join(basepath, 'gac', 'System.Web.Extensions', '1.0.61025.0__31bf3856ad364e35'):['System.Web.Extensions.dll','System.Web.Extensions.dll.mdb',],
    os.path.join(basepath, 'gac', 'policy.2.4.glade-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.4.glade-sharp.dll','policy.2.4.config',],
    os.path.join(basepath, 'gac', 'Mono.CompilerServices.SymbolWriter', '2.0.5.0__0738eb9f132ed756'):['Mono.CompilerServices.SymbolWriter.dll.mdb','Mono.CompilerServices.SymbolWriter.dll',],
    os.path.join(basepath, 'gac', 'policy.2.4.glib-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.4.config','policy.2.4.glib-sharp.dll',],
    os.path.join(basepath, 'gac', 'policy.2.6.atk-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.6.atk-sharp.dll','policy.2.6.config',],
    os.path.join(basepath, 'gac', 'policy.2.0.taglib-sharp', '0.0.0.0__db62eba44689b5b0'):['policy.2.0.taglib-sharp.config','policy.2.0.taglib-sharp.dll',],
    os.path.join(basepath, 'gac', 'rsvg2-sharp', '2.18.0.0__35e10195dab3c99f'):['rsvg2-sharp.dll.config','rsvg2-sharp.dll.mdb','rsvg2-sharp.dll',],
    os.path.join(basepath, 'gac', 'mod-mono-server', '2.4.0.0__0738eb9f132ed756'):['mod-mono-server.exe','mod-mono-server.exe.mdb',],
    os.path.join(basepath, 'gac', 'System.Core', '2.0.5.0__7cec85d7bea7798e'):['System.Core.dll.mdb','System.Core.dll',],
    os.path.join(basepath, 'gac', 'Gnome.Keyring', '1.0.0.0__1a73e1bde00c9b66'):['Gnome.Keyring.dll','Gnome.Keyring.dll.mdb',],
    os.path.join(basepath, 'gac', 'Novell.Directory.Ldap', '1.0.5000.0__0738eb9f132ed756'):['Novell.Directory.Ldap.dll','Novell.Directory.Ldap.dll.mdb',],
    os.path.join(basepath, 'gac', 'ICSharpCode.SharpZipLib', '0.6.0.0__1b03e6acf1164f73'):['ICSharpCode.SharpZipLib.dll','ICSharpCode.SharpZipLib.dll.mdb',],
    os.path.join(basepath, 'gac', 'System.Web.DynamicData', '3.5.0.0__31bf3856ad364e35'):['System.Web.DynamicData.dll.mdb','System.Web.DynamicData.dll',],
    os.path.join(basepath, 'compat-2.0'):['ICSharpCode.SharpZipLib.dll','System.Web.Extensions.dll','System.Web.Extensions.Design.dll',],
    os.path.join(basepath, 'gac', 'evolution-sharp', '5.0.0.0__c46a23b774189844'):['evolution-sharp.dll','evolution-sharp.dll.config','evolution-sharp.dll.mdb',],
    os.path.join(basepath, 'gac', 'System.Web', '2.0.0.0__b03f5f7f11d50a3a'):['System.Web.dll','System.Web.dll.mdb',],
    os.path.join(basepath, 'gac', 'policy.0.2.Mono.Addins.CecilReflector', '0.0.0.0__0738eb9f132ed756'):['policy.0.2.Mono.Addins.CecilReflector.dll','policy.0.2.config',],
    os.path.join(basepath, 'gac', 'Mono.Data.TdsClient', '2.0.0.0__0738eb9f132ed756'):['Mono.Data.TdsClient.dll','Mono.Data.TdsClient.dll.mdb',],
    os.path.join(basepath, 'gac', 'avahi-sharp', '1.0.0.0__4d116c78973743f5'):['avahi-sharp.dll.mdb','avahi-sharp.dll','avahi-sharp.dll.config',],
    os.path.join(basepath, 'gac', 'I18N.Rare', '2.0.0.0__0738eb9f132ed756'):['I18N.Rare.dll.mdb','I18N.Rare.dll',],
    os.path.join(basepath, 'gac', 'Mono.Posix', '1.0.5000.0__0738eb9f132ed756'):['Mono.Posix.dll.mdb','Mono.Posix.dll',],
    os.path.join(basepath, 'gac', 'ICSharpCode.SharpZipLib', '0.84.0.0__1b03e6acf1164f73'):['ICSharpCode.SharpZipLib.dll','ICSharpCode.SharpZipLib.dll.mdb',],
    os.path.join(basepath, 'ndesk-dbus-1.0'):['NDesk.DBus.dll',],
    os.path.join(basepath, 'gac', 'Mono.Messaging', '1.0.5000.0__b03f5f7f11d50a3a'):['Mono.Messaging.dll.mdb','Mono.Messaging.dll',],
    os.path.join(basepath, 'gac', 'I18N', '2.0.0.0__0738eb9f132ed756'):['I18N.dll','I18N.dll.mdb',],
    os.path.join(basepath, 'gac', 'System.ComponentModel.DataAnnotations', '3.5.0.0__31bf3856ad364e35'):['System.ComponentModel.DataAnnotations.dll','System.ComponentModel.DataAnnotations.dll.mdb',],
    os.path.join(basepath, 'gac', 'Microsoft.VisualC', '7.0.5000.0__b03f5f7f11d50a3a'):['Microsoft.VisualC.dll.mdb','Microsoft.VisualC.dll',],
    os.path.join(basepath, 'gac', 'Mono.Cairo', '2.0.0.0__0738eb9f132ed756'):['Mono.Cairo.dll','Mono.Cairo.dll.mdb',],
    os.path.join(basepath, 'webkit-sharp'):['webkit-sharp.dll',],
    os.path.join(basepath, 'gac', 'nunit.core', '2.4.8.0__96d09a1eb7f44a77'):['nunit.core.dll.mdb','nunit.core.dll',],
    os.path.join(basepath, 'gac', 'System', '2.0.5.0__7cec85d7bea7798e'):['System.dll.mdb','System.dll',],
    os.path.join(basepath, 'gac', 'System.Runtime.Remoting', '2.0.0.0__b77a5c561934e089'):['System.Runtime.Remoting.dll','System.Runtime.Remoting.dll.mdb',],
    os.path.join(basepath, 'gac', 'gconf-sharp-peditors', '2.24.0.0__35e10195dab3c99f'):['gconf-sharp-peditors.dll.mdb','gconf-sharp-peditors.dll',],
    os.path.join(basepath, 'gac', 'OpenSystem.C', '1.0.5000.0__b77a5c561934e089'):['OpenSystem.C.dll','OpenSystem.C.dll.mdb',],
    os.path.join(basepath, 'gac', 'System.Management', '2.0.0.0__b03f5f7f11d50a3a'):['System.Management.dll','System.Management.dll.mdb',],
    os.path.join(basepath, 'gac', 'System.Xml', '2.0.0.0__b77a5c561934e089'):['System.Xml.dll','System.Xml.dll.mdb',],
    os.path.join(basepath, 'gac', 'Mono.C5', '1.0.0.0__ba07f434b1c35cbd'):['Mono.C5.dll','Mono.C5.dll.mdb',],
    os.path.join(basepath, 'gac', 'System.Messaging', '1.0.5000.0__b03f5f7f11d50a3a'):['System.Messaging.dll','System.Messaging.dll.mdb',],
    os.path.join(basepath, 'gac', 'Novell.Directory.Ldap', '2.0.0.0__0738eb9f132ed756'):['Novell.Directory.Ldap.dll','Novell.Directory.Ldap.dll.mdb',],
    os.path.join(basepath, 'gac', 'IKVM.Runtime', '0.38.0.4__13235d27fcbfff58'):['IKVM.Runtime.dll',],
    os.path.join(basepath, 'gac', 'I18N.CJK', '1.0.5000.0__0738eb9f132ed756'):['I18N.CJK.dll.mdb','I18N.CJK.dll',],
    os.path.join(basepath, 'gac', 'pango-sharp', '2.12.0.0__35e10195dab3c99f'):['pango-sharp.dll.mdb','pango-sharp.dll.config','pango-sharp.dll',],
    os.path.join(basepath, 'gac', 'gmime-sharp', '2.2.0.0__677013d4cb5910f0'):['gmime-sharp.dll','gmime-sharp.dll.config',],
    os.path.join(basepath, 'gac', 'Mono.WebServer2', '0.2.0.0__0738eb9f132ed756'):['Mono.WebServer2.dll.mdb','Mono.WebServer2.dll',],
    os.path.join(basepath, 'gac', 'System.Windows.Forms', '2.0.0.0__b77a5c561934e089'):['System.Windows.Forms.dll.mdb','System.Windows.Forms.dll',],
    os.path.join(basepath, 'gac', 'Mono.Data.Sqlite', '2.0.0.0__0738eb9f132ed756'):['Mono.Data.Sqlite.dll.mdb','Mono.Data.Sqlite.dll',],
    os.path.join(basepath, 'gac', 'System.Xml', '1.0.5000.0__b77a5c561934e089'):['System.Xml.dll','System.Xml.dll.mdb',],
    os.path.join(basepath, 'gac', 'policy.2.10.gtk-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.10.gtk-sharp.dll','policy.2.10.config',],
    os.path.join(basepath, 'gac', 'gdk-sharp', '2.12.0.0__35e10195dab3c99f'):['gdk-sharp.dll.mdb','gdk-sharp.dll','gdk-sharp.dll.config',],
    os.path.join(basepath, 'gac', 'policy.2.8.gtk-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.8.gtk-sharp.dll','policy.2.8.config',],
    os.path.join(basepath, 'gac', 'webkit-sharp', '1.0.0.0__eaa1d335d2e19745'):['webkit-sharp.dll.config','webkit-sharp.dll',],
    os.path.join(basepath, 'gac', 'monodoc', '1.0.0.0__0738eb9f132ed756'):['monodoc.dll.mdb','monodoc.dll.config','monodoc.dll',],
    os.path.join(basepath, 'gac', 'policy.0.3.Mono.Addins.Setup', '0.0.0.0__0738eb9f132ed756'):['policy.0.3.Mono.Addins.Setup.dll','policy.0.3.config',],
    os.path.join(basepath, 'gac', 'avahi-ui-sharp', '0.0.0.0__4d116c78973743f5'):['avahi-ui-sharp.dll.mdb','avahi-ui-sharp.dll','avahi-ui-sharp.dll.config',],
    os.path.join(basepath, 'gac', 'Mono.Data', '2.0.0.0__0738eb9f132ed756'):['Mono.Data.dll.mdb','Mono.Data.dll',],
    os.path.join(basepath, 'gac', 'Mono.Data.SybaseClient', '1.0.5000.0__0738eb9f132ed756'):['Mono.Data.SybaseClient.dll','Mono.Data.SybaseClient.dll.mdb',],
    os.path.join(basepath, 'gac', 'System.Transactions', '2.0.0.0__b77a5c561934e089'):['System.Transactions.dll','System.Transactions.dll.mdb',],
    os.path.join(basepath, 'gac', 'Mono.Web', '2.0.0.0__0738eb9f132ed756'):['Mono.Web.dll.mdb','Mono.Web.dll',],
    os.path.join(basepath, 'gtksourceview-sharp-2.0'):['gtksourceview-sharp.dll',],
    os.path.join(basepath, 'gac', 'NDesk.DBus.GLib', '1.0.0.0__f6716e4f9b2ed099'):['NDesk.DBus.GLib.dll.mdb','NDesk.DBus.GLib.dll.config','NDesk.DBus.GLib.dll',],
    os.path.join(basepath, 'gac', 'System.ServiceProcess', '2.0.0.0__b03f5f7f11d50a3a'):['System.ServiceProcess.dll','System.ServiceProcess.dll.mdb',],
    os.path.join(basepath, 'gac', 'fastcgi-mono-server', '2.4.0.0__0738eb9f132ed756'):['fastcgi-mono-server.exe.mdb','fastcgi-mono-server.exe',],
    os.path.join(basepath, 'gac', 'xsp2', '2.4.0.0__0738eb9f132ed756'):['xsp2.exe','xsp2.exe.mdb',],
    os.path.join(basepath, 'gac', 'policy.0.2.Mono.Addins', '0.0.0.0__0738eb9f132ed756'):['policy.0.2.Mono.Addins.dll','policy.0.2.config',],
    os.path.join(basepath, 'gac', 'I18N.MidEast', '1.0.5000.0__0738eb9f132ed756'):['I18N.MidEast.dll','I18N.MidEast.dll.mdb',],
    os.path.join(basepath, 'gac', 'System.Xml', '2.0.5.0__7cec85d7bea7798e'):['System.Xml.dll','System.Xml.dll.mdb',],
    os.path.join(basepath, 'gac', 'System.Windows.Forms', '1.0.5000.0__b77a5c561934e089'):['System.Windows.Forms.dll.mdb','System.Windows.Forms.dll',],
    os.path.join(basepath, 'gac', 'I18N.MidEast', '2.0.0.0__0738eb9f132ed756'):['I18N.MidEast.dll','I18N.MidEast.dll.mdb',],
    os.path.join(basepath, 'gac', 'policy.2.8.glib-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.8.config','policy.2.8.glib-sharp.dll',],
    os.path.join(basepath, 'gac', 'Microsoft.Build.Engine', '2.0.0.0__b03f5f7f11d50a3a'):['Microsoft.Build.Engine.dll','Microsoft.Build.Engine.dll.mdb',],
    os.path.join(basepath, 'gac', 'gecko-sharp', '2.0.0.0__ccf7d78a55e9f021'):['gecko-sharp.dll','gecko-sharp.dll.config',],
    os.path.join(basepath, 'avahi-ui-sharp'):['avahi-ui-sharp.dll',],
    os.path.join(basepath, 'gtk-sharp-2.0'):['policy.2.10.atk-sharp.dll','policy.2.10.gdk-sharp.dll','glib-sharp.dll','policy.2.4.pango-sharp.dll','policy.2.8.glade-sharp.dll','policy.2.4.gtk-sharp.dll','policy.2.6.gtk-dotnet.dll','policy.2.6.gtk-sharp.dll','policy.2.6.atk-sharp.dll','policy.2.8.gtk-sharp.dll','gtk-dotnet.dll','gconf-sharp.dll','policy.2.4.atk-sharp.dll','policy.2.4.gtk-dotnet.dll','policy.2.10.pango-sharp.dll','policy.2.4.glade-sharp.dll','atk-sharp.dll','glade-sharp.dll','gtk-sharp.dll','policy.2.8.atk-sharp.dll','gnome-vfs-sharp.dll','policy.2.4.glib-sharp.dll','policy.2.10.gtk-sharp.dll','policy.2.10.glade-sharp.dll','pango-sharp.dll','policy.2.6.pango-sharp.dll','gconf-sharp-peditors.dll','policy.2.6.glib-sharp.dll','gdk-sharp.dll','policy.2.8.gtk-dotnet.dll','policy.2.6.gdk-sharp.dll','policy.2.10.gtk-dotnet.dll','policy.2.6.glade-sharp.dll','art-sharp.dll','policy.2.8.gdk-sharp.dll','gnome-sharp.dll','policy.2.8.pango-sharp.dll','policy.2.10.glib-sharp.dll','policy.2.4.gdk-sharp.dll','policy.2.8.glib-sharp.dll',],
    os.path.join(basepath, 'gac', 'policy.0.2.Mono.Addins.Gui', '0.0.0.0__0738eb9f132ed756'):['policy.0.2.Mono.Addins.Gui.dll','policy.0.2.config',],
    os.path.join(basepath, 'log4net'):['log4net.dll',],
    os.path.join(basepath, 'boo'):['Boo.Lang.Interpreter.dll','Boo.Lang.PatternMatching.dll','Boo.Lang.Parser.dll','Boo.Lang.dll','Boo.Lang.Compiler.dll','Boo.Lang.CodeDom.dll','Boo.Lang.Extensions.dll','Boo.Lang.Useful.dll',],
    os.path.join(basepath, 'gac', 'Microsoft.Vsa', '8.0.0.0__b03f5f7f11d50a3a'):['Microsoft.Vsa.dll','Microsoft.Vsa.dll.mdb',],
    os.path.join(basepath, 'gac', 'Microsoft.Build.Utilities', '2.0.0.0__b03f5f7f11d50a3a'):['Microsoft.Build.Utilities.dll.mdb','Microsoft.Build.Utilities.dll',],
    os.path.join(basepath, 'gac', 'xsp', '2.4.0.0__0738eb9f132ed756'):['xsp.exe.mdb','xsp.exe',],
    os.path.join(basepath, 'gac', 'Mono.CompilerServices.SymbolWriter', '1.0.5000.0__0738eb9f132ed756'):['Mono.CompilerServices.SymbolWriter.dll.mdb','Mono.CompilerServices.SymbolWriter.dll',],
    os.path.join(basepath, 'gac', 'nunit.core.interfaces', '2.4.8.0__96d09a1eb7f44a77'):['nunit.core.interfaces.dll','nunit.core.interfaces.dll.mdb',],
    os.path.join(basepath, 'gecko-sharp-2.0'):['gecko-sharp.dll',],
    os.path.join(basepath, 'gac', 'RabbitMQ.Client', '1.0.5000.0__b03f5f7f11d50a3a'):['RabbitMQ.Client.dll.mdb','RabbitMQ.Client.dll',],
    os.path.join(basepath, 'gac', 'Boo.Lang.Compiler', '2.0.0.0__32c39770e9a21a67'):['Boo.Lang.Compiler.dll.mdb','Boo.Lang.Compiler.dll',],
    os.path.join(basepath, 'gac', 'gtk-dotnet', '2.12.0.0__35e10195dab3c99f'):['gtk-dotnet.dll','gtk-dotnet.dll.config','gtk-dotnet.dll.mdb',],
    os.path.join(basepath, 'gac', 'mod-mono-server2', '2.4.0.0__0738eb9f132ed756'):['mod-mono-server2.exe.mdb','mod-mono-server2.exe',],
    os.path.join(basepath, 'gac', 'Accessibility', '2.0.0.0__b03f5f7f11d50a3a'):['Accessibility.dll','Accessibility.dll.mdb',],
    os.path.join(basepath, 'gac', 'System.ServiceProcess', '1.0.5000.0__b03f5f7f11d50a3a'):['System.ServiceProcess.dll','System.ServiceProcess.dll.mdb',],
    os.path.join(basepath, 'gac', 'Mono.Management', '2.0.0.0__0738eb9f132ed756'):['Mono.Management.dll.mdb','Mono.Management.dll',],
    os.path.join(basepath, 'mono-zeroconf'):['Mono.Zeroconf.dll',],
    os.path.join(basepath, 'gac', 'Boo.Lang', '2.0.0.0__32c39770e9a21a67'):['Boo.Lang.dll.mdb','Boo.Lang.dll',],
    os.path.join(basepath, 'gac', 'System.Web.Services', '2.0.0.0__b03f5f7f11d50a3a'):['System.Web.Services.dll.mdb','System.Web.Services.dll',],
    os.path.join(basepath, 'gac', 'OpenSystem.C', '2.0.0.0__b77a5c561934e089'):['OpenSystem.C.dll','OpenSystem.C.dll.mdb',],
    os.path.join(basepath, 'gac', 'Microsoft.VisualBasic', '7.0.5000.0__b03f5f7f11d50a3a'):['Microsoft.VisualBasic.dll',],
    os.path.join(basepath, 'gac', 'Mono.Zeroconf', '3.0.0.80__e60c4f4a95e1099e'):['Mono.Zeroconf.dll.mdb','Mono.Zeroconf.dll',],
    os.path.join(basepath, 'gac', 'System.Web.Extensions', '3.5.0.0__31bf3856ad364e35'):['System.Web.Extensions.dll','System.Web.Extensions.dll.mdb',],
    os.path.join(basepath, 'gac', 'Npgsql', '1.0.5000.0__5d8b90d52f46fda7'):['Npgsql.dll','Npgsql.dll.mdb',],
    os.path.join(basepath, 'rsvg2-sharp-2.0'):['rsvg2-sharp.dll',],
    os.path.join(basepath, 'gac', 'ICSharpCode.SharpZipLib', '2.84.0.0__1b03e6acf1164f73'):['ICSharpCode.SharpZipLib.dll','ICSharpCode.SharpZipLib.dll.mdb',],
    os.path.join(basepath, 'gac', 'notify-sharp', '0.4.0.0__2df29c54e245917a'):['notify-sharp.dll.config','notify-sharp.dll',],
    os.path.join(basepath, 'gac', 'System.Data.OracleClient', '1.0.5000.0__b77a5c561934e089'):['System.Data.OracleClient.dll.mdb','System.Data.OracleClient.dll',],
    os.path.join(basepath, '2.0', 'MSBuild'):['Microsoft.Build.Core.xsd','Microsoft.Build.CommonTypes.xsd',],
    os.path.join(basepath, 'gac', 'policy.2.6.pango-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.6.pango-sharp.dll','policy.2.6.config',],
    os.path.join(basepath, 'gac', 'System.Net', '2.0.5.0__7cec85d7bea7798e'):['System.Net.dll.mdb','System.Net.dll',],
    os.path.join(basepath, 'gac', 'System.Design', '1.0.5000.0__b03f5f7f11d50a3a'):['System.Design.dll.mdb','System.Design.dll',],
    os.path.join(basepath, 'gac', 'gnome-sharp', '2.24.0.0__35e10195dab3c99f'):['gnome-sharp.dll.config','gnome-sharp.dll.mdb','gnome-sharp.dll',],
    os.path.join(basepath, 'gac', 'Mono.Addins.CecilReflector', '0.4.0.0__0738eb9f132ed756'):['Mono.Addins.CecilReflector.dll','Mono.Addins.CecilReflector.dll.mdb',],
    os.path.join(basepath, 'gac', 'System.Runtime.Serialization.Formatters.Soap', '1.0.5000.0__b03f5f7f11d50a3a'):['System.Runtime.Serialization.Formatters.Soap.dll','System.Runtime.Serialization.Formatters.Soap.dll.mdb',],
    os.path.join(basepath, 'gac', 'gtkhtml-sharp', '3.16.0.0__35e10195dab3c99f'):['gtkhtml-sharp.dll.config','gtkhtml-sharp.dll.mdb','gtkhtml-sharp.dll',],
    os.path.join(basepath, 'gac', 'Npgsql', '2.0.0.0__5d8b90d52f46fda7'):['Npgsql.dll','Npgsql.dll.mdb',],
    os.path.join(basepath, 'gac', 'System.Data.DataSetExtensions', '3.5.0.0__b77a5c561934e089'):['System.Data.DataSetExtensions.dll.mdb','System.Data.DataSetExtensions.dll',],
    os.path.join(basepath, 'gac', 'Mono.Data.SqliteClient', '1.0.5000.0__0738eb9f132ed756'):['Mono.Data.SqliteClient.dll','Mono.Data.SqliteClient.dll.mdb',],
    os.path.join(basepath, 'gac', 'Boo.Lang.Extensions', '2.0.0.0__32c39770e9a21a67'):['Boo.Lang.Extensions.dll.mdb','Boo.Lang.Extensions.dll',],
    os.path.join(basepath, 'gac', 'Mono.GetOptions', '2.0.0.0__0738eb9f132ed756'):['Mono.GetOptions.dll','Mono.GetOptions.dll.mdb',],
    os.path.join(basepath, 'gac', 'policy.0.2.Mono.Addins.Setup', '0.0.0.0__0738eb9f132ed756'):['policy.0.2.config','policy.0.2.Mono.Addins.Setup.dll',],
    os.path.join(basepath, 'gac', 'Mono.Cecil', '0.6.9.0__0738eb9f132ed756'):['Mono.Cecil.dll.mdb','Mono.Cecil.dll',],
    os.path.join(basepath, 'gac', 'Mono.Security', '1.0.5000.0__0738eb9f132ed756'):['Mono.Security.dll.mdb','Mono.Security.dll',],
    os.path.join(basepath, 'gac', 'Mono.Http', '1.0.5000.0__0738eb9f132ed756'):['Mono.Http.dll','Mono.Http.dll.mdb',],
    os.path.join(basepath, 'gac', 'Microsoft.Vsa', '7.0.5000.0__b03f5f7f11d50a3a'):['Microsoft.Vsa.dll','Microsoft.Vsa.dll.mdb',],
    os.path.join(basepath, 'gac', 'System.Drawing.Design', '2.0.0.0__b03f5f7f11d50a3a'):['System.Drawing.Design.dll.mdb','System.Drawing.Design.dll',],
    os.path.join(basepath, 'gac', 'Mono.Data', '1.0.5000.0__0738eb9f132ed756'):['Mono.Data.dll.mdb','Mono.Data.dll',],
    os.path.join(basepath, 'gac', 'policy.2.4.gdk-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.4.config','policy.2.4.gdk-sharp.dll',],
    os.path.join(basepath, 'gac', 'nunit.framework', '2.4.8.0__96d09a1eb7f44a77'):['nunit.framework.dll.mdb','nunit.framework.dll',],
    os.path.join(basepath, 'gac', 'Mono.Data.Tds', '2.0.0.0__0738eb9f132ed756'):['Mono.Data.Tds.dll','Mono.Data.Tds.dll.mdb',],
    os.path.join(basepath, 'gac', 'nunit-console-runner', '2.4.8.0__96d09a1eb7f44a77'):['nunit-console-runner.dll.mdb','nunit-console-runner.dll',],
    os.path.join(basepath, 'gmime-sharp'):['gmime-sharp.dll',],
    os.path.join(basepath, 'gac', 'Mono.Messaging.RabbitMQ', '2.0.0.0__b03f5f7f11d50a3a'):['Mono.Messaging.RabbitMQ.dll.mdb','Mono.Messaging.RabbitMQ.dll',],
    os.path.join(basepath, 'gac', 'I18N.West', '2.0.0.0__0738eb9f132ed756'):['I18N.West.dll.mdb','I18N.West.dll',],
    os.path.join(basepath, 'gac', 'Mono.WebServer', '0.1.0.0__0738eb9f132ed756'):['Mono.WebServer.dll.mdb','Mono.WebServer.dll',],
    os.path.join(basepath, 'gac', 'Mono.Addins', '0.4.0.0__0738eb9f132ed756'):['Mono.Addins.dll','Mono.Addins.dll.mdb','Mono.Addins.dll.config',],
    os.path.join(basepath, 'gac', 'Mono.Data.Sqlite', '1.0.5000.0__0738eb9f132ed756'):['Mono.Data.Sqlite.dll.mdb','Mono.Data.Sqlite.dll',],
    os.path.join(basepath, 'gac', 'I18N', '1.0.5000.0__0738eb9f132ed756'):['I18N.dll','I18N.dll.mdb',],
    os.path.join(basepath, 'gac', 'Boo.Lang.PatternMatching', '2.0.0.0__32c39770e9a21a67'):['Boo.Lang.PatternMatching.dll','Boo.Lang.PatternMatching.dll.mdb',],
    os.path.join(basepath, 'gac', 'System.Configuration', '2.0.0.0__b03f5f7f11d50a3a'):['System.Configuration.dll','System.Configuration.dll.mdb',],
    os.path.join(basepath, 'gac', 'gsf-sharp', '0.0.0.7__35e10195dab3c99f'):['gsf-sharp.dll.config','gsf-sharp.dll',],
    os.path.join(basepath, 'compat-1.0'):['ICSharpCode.SharpZipLib.dll',],
    os.path.join(basepath, 'gac', 'System.Configuration.Install', '1.0.5000.0__b03f5f7f11d50a3a'):['System.Configuration.Install.dll','System.Configuration.Install.dll.mdb',],
    os.path.join(basepath, 'gac', 'System.Data', '1.0.5000.0__b77a5c561934e089'):['System.Data.dll.mdb','System.Data.dll',],
    os.path.join(basepath, 'gac', 'Mono.Data.SybaseClient', '2.0.0.0__0738eb9f132ed756'):['Mono.Data.SybaseClient.dll','Mono.Data.SybaseClient.dll.mdb',],
    os.path.join(basepath, 'gac', 'policy.2.8.gdk-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.8.config','policy.2.8.gdk-sharp.dll',],
    os.path.join(basepath, 'gac', 'I18N.CJK', '2.0.0.0__0738eb9f132ed756'):['I18N.CJK.dll.mdb','I18N.CJK.dll',],
    os.path.join(basepath, 'gac', 'policy.2.8.pango-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.8.config','policy.2.8.pango-sharp.dll',],
    os.path.join(basepath, 'gac', 'taglib-sharp', '2.0.3.2__db62eba44689b5b0'):['taglib-sharp.dll.mdb','taglib-sharp.dll',],
    os.path.join(basepath, 'gac', 'art-sharp', '2.24.0.0__35e10195dab3c99f'):['art-sharp.dll.mdb','art-sharp.dll.config','art-sharp.dll',],
    os.path.join(basepath, 'gac', 'policy.2.6.gdk-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.6.config','policy.2.6.gdk-sharp.dll',],
    os.path.join(basepath, 'gac', 'System.Core', '3.5.0.0__b77a5c561934e089'):['System.Core.dll.mdb','System.Core.dll',],
    os.path.join(basepath, 'gac', 'policy.2.4.atk-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.4.atk-sharp.dll','policy.2.4.config',],
    os.path.join(basepath, 'gac', 'policy.2.6.glib-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.6.glib-sharp.dll','policy.2.6.config',],
    os.path.join(basepath, 'gac', 'policy.2.10.atk-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.10.atk-sharp.dll','policy.2.10.config',],
    os.path.join(basepath, 'gac', 'nunit.mocks', '2.4.8.0__96d09a1eb7f44a77'):['nunit.mocks.dll.mdb','nunit.mocks.dll',],
    os.path.join(basepath, 'gac', 'policy.2.10.glib-sharp', '0.0.0.0__35e10195dab3c99f'):['policy.2.10.config','policy.2.10.glib-sharp.dll',],
    os.path.join(basepath, 'dbus-sharp'):['dbus-sharp.dll',],
}

symlinks = {
}

